### ISSUE TITLE
Add Czech language support

### ISSUE THREAD

**Issue by bartektartanus** [languagetool-org/languagetool#1030]

**Comment by danielnaber** [comment]
Are you planning to contribute support for Czech? Here are some details about how to write error detection rules without programming: http://wiki.languagetool.org/development-overview

**Comment by danielnaber** [comment]
Okay, but then I'll close this issue as it doesn't help to have an open issue for every language not yet supported.

**Comment by ferenczy** [comment]
So I guess there's currently no work in progress on adding the Czech language or there never been any before, right?

I would like to start working on that if amount of my spare time allows it. I'm a software engineer so I won't have issues with implementing it.

I was just surprised that a language is implemented as a collection of Java classes, I expected it will be just data (rules). It's kind of stupid that adding a language requires a software engineer instead of a language scientist. Why is that? Is it because various languages are so different that it's not possible to implement a common processing for all languages using rules defined as data? Wouldn't it be flexible enough to implement various spell check for various languages?

**Comment by danielnaber** [comment]
As far as I remember, nobody has worked on Czech recently. How to write rules manually is documented at http://wiki.languagetool.org/development-overview, but that's only one way to detect errors. [Statistics can be used](http://wiki.languagetool.org/finding-errors-using-big-data) or Java code.

> One more question - what are the translations on Transifex good for? I guess that's just for user interface localization, right?

Exactly.
