### ISSUE TITLE
install script doesn't work

### ISSUE THREAD

**Issue by luxe** [languagetool-org/languagetool#1150]
```
curl -L https://git.io/vNqdP | sudo bash
...
Error: spellcheck.txt does not exist, and no text to be checked was specified.
```

**Comment by danielnaber** [comment]
@InnovativeInventor any idea?

**Comment by InnovativeInventor** [comment]
That's strange. This should only appear if you pass -c cmdline to the script and the file you specified to spell check (default is spellcheck.txt) doesn't exist. 

I believe the error is here:
```
if ! [ "$(type -t DISPLAY)" ]; then
    if ! [ "$command" ]; then <--
        command="commandline"
    fi
    display='no'
fi
```
This is meant to default to running LanguageTool through the command line if a command is specified and there is no display (to prevent the gui from running when it shouldn't, even if the user specifies it). This should all be fixed in pull request #1151.

**Comment by hliebert** [comment]
I am seeing the same error message on a new installation of Ubuntu 18.04.

**Comment by InnovativeInventor** [comment]
The link in the README points to an old version of the install script. Try using 
```
curl -L https://raw.githubusercontent.com/languagetool-org/languagetool/master/install.sh | sudo bash
```

**Comment by danielnaber** [comment]
Does anybody actually type this URL and *not* just copy and paste it? I don't really see the need for a link shortener?

**Comment by InnovativeInventor** [comment]
It is also easier to remember. Also, if someone is using a computer with only a terminal, copying and pasting doesn't work. Most projects have it as a get.website.url or install.website.url. I just thought it would be better to follow that.

**Comment by danielnaber** [comment]
I don't want to set up install.languagetool.org as it's yet another thing that needs to be maintained. Please let me know the new link (shortened or not).

**Comment by InnovativeInventor** [comment]
```
https://raw.githubusercontent.com/languagetool-org/languagetool/master/install.sh
```
will always point to the latest version of the install script on master.

**Comment by danielnaber** [comment]
I assume this can be closed, please re-open if that's not the case.
