### ISSUE TITLE
languagetool-server systemd support

### ISSUE THREAD

**Issue by zabbal** [languagetool-org/languagetool#124]
Adding support for systemd's .socket and .service files to languagetool-server via socket activation would make code upgrade easier and will simplify integration with modern GNU/Linux distributions.

**Comment by ronnystandtke** [comment]
Sorry for necro bumping this issue, but I just wanted to integrate languagetool-server into a Linux distribution for schools and run into exactly this issue.
We could save a lot of precious system resources by starting languagetool-server on demand via socket activation. The additional code required is not complex at all. In fact, it is *ONE* line of java code. Here is how the fine folks of gerrit dit it:
https://opendev.org/opendev/gerrit/commit/aa93fdfe071b0223722dd1e978e1687a064ca950

Please reconsider supporting socket activation of languagetool-server.

**Comment by hopp19** [comment]
This is a request for re-opening this issue.

1. Add my +1 to this issue.
1. I think @ronnystandtke has a point in that this request barely adds any complexity to LT.
1. Providing support for socket activation can certainly improve boot-up user experience with offline installations on resource constrained hardware, such as consumer-grade desktop or mobile devices where CPU and memory may not be plenty available.  Because activated via socket, LanguageTool is not sucked-in to memory at startup, but only at first use, which may well be hours later or not at all during a session.

Thanks for considering this!

**Comment by solonovamax** [comment]
As much as I would like to see this implemented, given that languagetool is using `com.sun.net.httpserver.HttpServer` rather than something like Jetty or Netty, I'm not so sure that this is possible without rewriting languagetool to use either Jetty or Netty.

looking at Jetty's docs for [`ServerConnector#setInheritChannel(boolean)`](https://javadoc.jetty.org/jetty-12/org/eclipse/jetty/server/ServerConnector.html#setInheritChannel(boolean)):
> Sets whether this connector uses a channel inherited from the JVM.
> 
> If true, the connector first tries to inherit from a channel provided by the system. If there is no inherited channel available, or if the inherited channel is not usable, then it will fall back using [ServerSocketChannel](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/channels/ServerSocketChannel.html).
> 
> Use it with xinetd/inetd, to launch an instance of Jetty on demand. The port used to access pages on the Jetty instance is the same as the port used to launch Jetty.

however there is no such similar setting for `HttpServer`, it only exposes which `InetSocketAddress` you wish to listen to.
looking even further into it, it eventually instantiates a `ServerImpl` instance which has the following in its constructor:
```java
schan = ServerSocketChannel.open();
```

I believe that if you wanted to be able to make it work with systemd socket activation, it would have to be possible to replace this call with a call instead to [`System#inheritedChannel()`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/System.html#inheritedChannel())

as such, unless they wish to rewrite the languagetool server to use Jetty or Netty (which although it might improve performance, would also take a bunch of effort), it's not feasible to add support for this
