### ISSUE TITLE
Hunspell version

### ISSUE THREAD

**Issue by loretoparisi** [languagetool-org/languagetool#1276]
Which version of Hunspell the language tool implements? There is a upcoming v1.7 version almost ready.
Thank you.

**Comment by baarsrj** [comment]
The 1.7 version seems to be able to do a lot more, and could be a bit faster. For the new functions to be used, the .dic and .aff have to be changed for the languages. With unchanged data files, only a slight improvement appears to be the result.
I will test it as soon as it appears to be finished

**Comment by danielnaber** [comment]
Is this still relevant? Upgrading hunspell doesn't seem trivial (we need to use it from Java), so unless there are clear benefits, this does not seem too important?

**Comment by baarsrj** [comment]
Have not seen any updates of Hunspell since then. Github of Hunspell is very quiet. I guess we can forget this for now. Hunspell on my machine is showing version 2.0.0 however, so it was silently updated with all other stuff. Since I do not know how Hunspell has been integrated, I would not know if it is worth the effort updating the Hunspell that LT uses.
