### ISSUE TITLE
[NL] Ideas for rules

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1346]
A Dutch learner suggests these rules. @baarsrj Maybe you can have a look?

It doesn't seem to deal well with singular/plural:
Correct: Hij ziet het meisje
Incorrect: Hij zien het meisje

Dutch has de/het words. While it picks up cases where de/het is used incorrectly it doesn't check related/secondary words that are also affected by this. For example:
Correct: Het jaar is lang. De week is lang.
Incorrect: De jaar is lang. Het week is lang.
=> This it picks up, however there is also a rule that says when you use "volgende" it changes form based on whether it is a "de" or "het" word. For example
Correct: Het volgend jaar. De volgende week.
Incorrect: Het volgende jaar. De volgend week.

**Comment by baarsrj** [comment]
@danielnaber 
To be honest, the language learner is right. LT is not good at this. But there is a reason for this: ambiguous words and the flexibility of Dutch creates loads of false positives when a rule as simple as suggested were made. In fact, I gave it a go, but gave up in the end.
Some examples:
'het volgend jaar' would be incorrect, but not in a construction like 'Al je het volgend jaar doet'. Because 'het' is not the article here. But that decision can only be made when the sentence has been analysed (and resulted unambiguous) in full. A full brill tagger might help, but is probably not good enough either; looking at the results of some of those.
Another example is 'de fiancieel (rule would suggest financiële) directeur'. A common exception because the 'financieel' is not really an attribute of the 'directeur'. Same for 'een groot kampioen' (rule would suggest grote).
Dutch is quite hard to learn. Not just for people; for computers too. One way to go would be using machine learning, professionally edited texts in large quantities and professional language teachers for training. Unfortunately, we don't have that capability. Would be hard to do for free anyway. 
Anyway... the language learner is very welcome to contact me directly or by using the forum.

**Comment by evs-xsarus** [comment]
Maybe I'm missing it, but verbs don't seem to be checked. I'm using extension 4.4.1 for LibreOffice.

Correct: Hij loopt op straat.
Incorrect: Hij loop op straat.

Correct: Vind jij het leuk?
Incorrect: Vindt jij het leuk?

Correct: Jij fietst snel.
Incorrect: Jij fiets snel.

![image](https://user-images.githubusercontent.com/44158071/52407791-80dcdb80-2ad1-11e9-8cb4-463fae3cc667.png)

De blue underlined words state 'Nadruk' (emphasis), see https://onzetaal.nl/taaladvies/wij-we

**Comment by baarsrj** [comment]
Dat klopt. In deze korte zinnen is het gemakkelijk te controleren, maar in langere niet. We zullen eens zien of het lukt om voor deze gevallen regels te maken.

**Comment by evs-xsarus** [comment]
Dat zou heel fijn zijn. Is het bekend hoe Microsoft die controles doet?

**Comment by baarsrj** [comment]
Nee, en ik wil het niet weten ook. Geen MS te vinden in mijn omgeving.

**Comment by baarsrj** [comment]
Overigens hebben we ons 10 jaar lang geconcentreerd op de meer serieuze teksten; daar komen dit soort basisfout niet in voor.

**Comment by evs-xsarus** [comment]
Ah, dat verklaart e.e.a. . Is het moment daar om over te stappen naar teksten die de huidige lichting scholieren typt? Als dan de language-tool bv. standaard wordt meegeleverd met LibreOffice, gaat hun aantal grammaticafouten hopelijk omlaag.

Ik vind het wel interessant om conceptregels te maken, hopelijk heb ik daar binnenkort tijd voor.

**Comment by baarsrj** [comment]
Voor 'hij loop' is overigens wel een regel. Daar zijn dan weer zo veel uitzonderingen op waarbij de werkwoordvorm een zelfstandig naamwoord is dat daar wel past.

**Comment by baarsrj** [comment]
We houden ons overigens aanbevolen voor deregelijke teksten. Die zijn namelijk niet zo gemakkelijk te verkrijgen (met toestemming). Maar met combinaties van foute en gecorrigeerde zinnen zijn we ook blij. Dan wel graag op het forum.
