### ISSUE TITLE
Brazilian Portuguese and European Portuguese

### ISSUE THREAD

**Issue by Robert321245** [languagetool-org/languagetool#1354]
Brazilian Portuguese and European Portuguese are essentially the same language, just like British English and American English, the differences are in the writing of some words.
Nevertheless, there are considerable differences between the two dictionaries in LanguageTools.
To know if a text I made is right, I have to write it using a dictionary and at the end, change the dictionary to see if there are wrong words the first one didn't get.

You could try to merge the two dictionaries and make the selection of pt-pt and pt-br changing only the spelling of some words, but letting all the rest of the words the same.

**Comment by kinow** [comment]
Not sure if the issue is to merge both dictionary/grammar checkers... if so...

>Brazilian Portuguese and European Portuguese are essentially the same language, just like British English and American English, the differences are in the writing of some words.

I see both languages much more distant than American and British English. They are different in spelling, use of verb tenses, and terminology. And while I can understand Portuguese from Portugal, it normally takes a few minutes, and I have to concentrate really hard, and I still miss some sentences (i.e. I cannot understand everything from news, or normal conversations)

Used a Portuguese online newspaper to search for some examples. But if I used a Portuguese blog the difference would be much clearer (some newspapers are following the new Portuguese after the acordo ortografico, though it's not followed by all newspapers in Brazil and Portugal [and this is [not the first](https://pt.wikipedia.org/wiki/Acordo_ortogr%C3%A1fico) accorded language change for Portuguese]).

## spelling

- facto @pt-pt, fato @pt-br
- penáltis @pt-pt, pênaltis @pt-br
- equipa @pt-pt, equipe @pt-br (equipa is only a way to conjugate the verb equipar, to equip, for pt-BR)
- prémios @pt-pt, prêmios @pt-br

## verb tenses

- ["o jornal inglês "The Sun" a dar destaque à intervenção"](https://www.jn.pt/desporto/interior/assistencia-de-varandas-a-adepto-foi-noticia-em-inglaterra-10496725.html), the "a dar destaque" would not appear in Brazilian Portuguese. It would always be "a destacar".
- ["jogadores do Sporting a festejarem a conquista"](https://www.jn.pt/desporto/interior/assistencia-de-varandas-a-adepto-foi-noticia-em-inglaterra-10496725.html), "a festejarem" in Brazilian Portuguese would actually be "festejando a conquista". In Brazilian Portuguese the gerund is used a lot more than in Portugal. That form is still used in some cases in Brazilian Portuguese (e.g. "eles se puseram a festejar a conquista"), but it depends on the verb, situation, context (i.e. different rules for each Portuguese).

## terminology

- ["Horas depois, a publicação foi eliminada"](https://www.jn.pt/nacional/interior/o-mamadou-e-se-fosses-bardamerda-deputado-do-psd-critica-assessor-do-be-10496769.html), "eliminada" here makes no sense in Brazilian Portuguese. We use it only for competitions, especially soccer. We would use something like "nullified" (anulada).
- ["usou a sua conta de Facebook"](https://www.jn.pt/nacional/interior/o-mamadou-e-se-fosses-bardamerda-deputado-do-psd-critica-assessor-do-be-10496769.html). The preposition "de" sounds weird in Brazilian Portuguese. I would probably rarely use for Twitter, FaceBook, Google, etc... it would always be "do" (conta do Facebook, conta do Twitter, conta do Google, etc)

## different words

- bófia, slang for police, but only in Portugal
- coxinha, slang for police or some political party, but only in Brazil (also a dish from Brazil, or just the diminutive of the word "coxa" thigh)
- contabilista, an accountant, is an old term, not used any more in Brazil, where we use "contador" or "profissional da contabilidade" instead. You may find this in old books, but not in newspapers (I believe there were some decrees to change the name of the profession, before my father was born around 50's)
- caleira, the rain gutter. It used to be called caleira in Brazil too, but now this word is not any longer. Instead it is used calha.

Everybody in Brazil has some words that are bad-words for us (offensive in many cases) that are used everyday in Portugal, and vice-versa. These are important to be separated when proof-reading a text in pt-pt or pt-br.

## Diminutive

In Brazilian Portuguese, the diminutive is used with high frequency. For an academic text, there are legit use cases for the diminutive (e.g. frango a passarinho, jeitinho), but there could exist a rule to avoid using it excessively.

It is possible to sound child-ish, girly, etc, by the use of the diminutive in Brazilian Portuguese ([e.g.](http://www.periodicos.ufpb.br/ojs/index.php/dclv/article/view/14092)). From what I learned from friends from Portugal (mainly Lisbon), it's not quite so common over there (and I don't see it in blogs/software/newspapers/tv).

## Cultural background

### Immigration

Brazil received a lot of immigrants, so there are lots of loanwords used, especially in Sao Paulo:

- shoyu - soy sauce, also called molho de soja
- hashi - chopsticks (or "palitinhos")
- site - site (not sure why we never adopted sítio as in Portugal)
- tablet - tablet (I think in Portugal they also use tablete? Which I would understand in the context)
- truco, a card game common in argentine/brazil
- nona and nono, for Italian grandparents (though normal in tv soap operas, and amongst descendants, it would not appear in a formal text)

There are also words that are common near borders with other countries, such as mate for chimarrao, or chimichurri (bbq sauce from Argentina).

There is also influence from African languages, Arabic, and native languages.

### Arabic influence

Portugal had an Arabic strong influence while it was under its dominance. It influenced the [language](https://en.wikipedia.org/wiki/Influence_of_Arabic_on_other_languages#Portuguese) too. But some of these words were not brought to Brazil. So in Portugal they may use "alforreca" for jellyfish, whereas in Brazil it would be "agua-viva". There are two or three other words which I heard used in Lisbon and learned later they were also from Arabic (but I can recall the words now, sorry).

In Brazil we had Arabic influence much later, coming through immigration. So certain words appear to have eroded too. Like the sfihas, a street food, which in Portugal is called "esfirra", but in Brazil it is called "esfiha". 

### Native indigenous people influence

Words from indigenous languages like Açaí, tapioca, carioca, caju (cashew), jacarandá, and capivara (Capybara) were exported, and are common even in distant places like Oceania (where I'm right now).

Some words like "capim" (grass, from where capy-bara [kapii-wára, from Tupi eat-grass] name comes from) but others I believe have not been adopted by Portuguese. Like "abacaxi" (their ananas, pineapple), and others (e.g. bauru, beiju, canga [means something else in Portugal], catapora, cupim, jacare, jiboia, cipó, arapuca

---

Here's an good text in English [Portuguese – Brazilian & European](http://thelanguagectr.com/wp-content/uploads/2012/11/Portuguese-Brazilian-European.pdf) about some of the differences.

Cheers
Bruno

p.s.: there are many bubbles within Brazil, where the language varies a lot (more than in Portugal). So there are areas where the Brazilian Portuguese can be much closer to continental Portuguese. See [this Wikipedia page](https://pt.wikipedia.org/wiki/L%C3%ADnguas_do_Brasil) for an example. Many cities adopt two or more languages, causing even more interesting variations of Portuguese!

p.s.2.: the native languages are not exactly Brazilian native.... they are American native. As there were no border for those natives, and languages like Guarani, the most used in Brazil I think, is also second-language in Paraguay (learned that through soccer, as their teams are able to communicate in Guarani, and Brazilian/Spanish speaker players are not able to understand what they are planning :soccer: )

**Comment by TiagoSantos81** [comment]
@kinow Thank you for the detailed answer. It is had to add anything to iy.

@Robert321245  If I understand correctly, I believe that you suggest that both dictionaries share a common root, which is truth. As an educated guess, I would say that more than 90% of the words are the same in both Portuguese variants. It would be nice to have a dictionary with those and have only a complementary dictionary for each variant with the diverging spellings. However, both hunspell dictionaries where built in very different ways, so it would required massive work to do such thing.
If you know a team that:
* 'unmunches' all variants, 
* creates a root dictionary with the forms that are present in all dictionaries, 
* recompiles the dictionaries  with the affixing and suffixing mechanisms used in hunspell to compress files, 
* does a pull request with the LT needed changes for using complementary hunspell dictionaries... 

I will definitely use it, but until all those are met, I will leave this issue as closed.
