### ISSUE TITLE
Error not found : c'est le/la terre

### ISSUE THREAD

**Issue by lemikeone** [languagetool-org/languagetool#1390]
When I write in french "Voici le facture", no issue is detected. 

Correct sentence should be "Voici la facture". 

https://snag.gy/ogxOEB.jpg

Thanks,

**Comment by Jesse-Penber** [comment]
This appears to only happen if there is another word before "le facture". On its own, "le facture" correctly highlights yellow. 

![facture](https://user-images.githubusercontent.com/41349257/52378484-a0fe9300-2a1c-11e9-842f-cf90f9065aaf.PNG)

This appears to be true for many feminine nouns if begun with "le" instead of "la".
Examples that all falsely validate as no error: Voici le vache, c'est le pelle, c'est le terre.

![image](https://user-images.githubusercontent.com/41349257/52378503-b4a9f980-2a1c-11e9-93b2-89e3d8d94ddc.png)

Masculine nouns that are begun with "la" are correctly highlighted in yellow.
Example: C'est la bateau, c'est la manteau, voici la manteau

![image](https://user-images.githubusercontent.com/41349257/52378525-c25f7f00-2a1c-11e9-9f93-2b487170809d.png)

**Comment by dpelle** [comment]
```
$ echo "C'est le pelle." | 
 java -jar  /home/pel/sb/languagetool/languagetool-standalone/target/LanguageTool-4.5-SNAPSHOT/LanguageTool-4.5-SNAPSHOT/languagetool-commandline.jar -c utf-8 -l fr -v -
Expected text language: French
Working on STDIN...
2776 rules activated for language French
<S> C[C/]'[C'/</CE>]est[est/N m s,être/V etre ind pres 3 s] le[le/D m s] pelle[pelle/N f s,peller/V imp pres 2 s,peller/V ind pres 1 s,peller/V ind pres 3 s,peller/V sub pres 1 s,peller/V sub pres 3 s].[./M fin,</S>]<P/> 
Disambiguator log: 

MULTIWORD_CHUNKER: C[C/N m sp*,c/N m sp*,c/R dem e s*] -> C[C/N m sp*,c/N m sp*,c/R dem e s*,C'/<CE>*]
ROMAN_NUMBER[1]: C[C/N m sp*,c/N m sp*,c/R dem e s*,C'/<CE>*] -> C[C/*]

MULTIWORD_CHUNKER: '['/null*] -> '[C'/</CE>*]

RB-LE_LA_LES[1]: le[le/D m s,le/R pers obj 3 m s] -> le[le/D m s]
```

So "pelle" can be a femine nound, but also a verb and it's most certainly why LT does not complain.
The disambiguator could be improved he to classify it as noun only.

I'll try to improve it.

I see that disambiguation of "C" could also be improved here even if that does not contribute to the false negative here at least.
