### ISSUE TITLE
[en] GUI and Java EN_WORD_COHERENCY: traumatisation

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#1452]
In the GUI, Java rule EN_WORD_COHERENCY gives a warning for the word _traumatisation_. But, there is only that one word in the text:
![image](https://user-images.githubusercontent.com/5816160/53949513-157f2d00-40c2-11e9-9342-cc3a1e552456.png)
The problem does not occur on languagetool.org.
I first noticed the problem yesterday with a snapshot that was a couple of days old. This screen shot is from LanguageTool-20190306-snapshot.

**Comment by f-knorr** [comment]
The reason for this behavior: 'traumatisation' has two postags with different lemmas (traumatisation, NN:UN and traumatization, NNS).
This problem could be fixed be using consistent an lemma: 'traumatisation' **or** 'traumatization'

I guess this error is also detected in the online version but does not become visible due to another error masking this one.

**Comment by MikeUnwalla** [comment]
> This problem could be fixed be using consistent an lemma
Thanks. I didn't see that. I will fix the error.
