### ISSUE TITLE
Add check box or other means to disable Grammar and Style Tab

### ISSUE THREAD

**Issue by TiagoSantos81** [languagetool-org/languagetool#1455]
This is an enhancement suggestion. Many languages already possess a large set of Style rules. Some maintainers prefer to disable (default='off') style rules with many detections, since some people don't use them and, they, due to their prevalence, may mask more important issues, like spelling problems or grammar.
Given the way that the Options panel is designed, I think that a few improvements could be made, to offer a better fit to user's needs, while still allowing LanguageTool to show all its available aids. I will give some examples of solutions that come to my mind:

* Identify the category of the rule and, in addition to the Ignore All, have a "Ignore category' option.
* Add check boxes next to the label of 'Grammar' and 'Style' tabs, so that users can disable one category in one document, but keep the enabled rule structure intact.
* Add one drop down list to the 'General tab' where the following options would be available: 
     -- Spelling, Grammar, and Style Rules;
     -- Spelling, and Grammar Rules;
     -- Spelling Rules Only;

**Comment by FredKruse** [comment]
the option panel was changed in that way, that a user can define profiles. This is a little more general way as discussed in this issue. All adjustments that was mentioned above (and much more special) can be done by definition of a profile for them. So I think the issue is solved.
@TiagoSantos81: Please test the new version. If you agree, the issue can be closed

**Comment by TiagoSantos81** [comment]
This is different but it is a great solution. I will close now.
