### ISSUE TITLE
User feedback about errors not found

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1482]
"The spell checker can't find the 9 errors in this simple text"

```
Bonjour les ami virtuelles comment aller-vous. Moi ca va tres bian.
Les feuilles morte se ramasse à la pelles.
```

**Comment by PoorPocketsMcNewHold** [comment]
Well, he does know how to fix some of them.
![image](https://user-images.githubusercontent.com/13170204/55876235-6ee1ec80-5b97-11e9-8b8f-28e41485f0a3.png)
After the check, it output the following text :+1: 

> Bonjour les amis virtuels comment allez-vous. Moi ça va très bien.
Les feuilles mortes se ramasse à la pelles.

It missed :

- The comma after virtuels (But it’s still technically working without it, as a comma is mostly used to make a pause for making the phrase to be easy readable or just easier to be spelled)

- The exclamation point after ¨comment allez-vous¨, this sentence is a question, I don’t really see how we can fix that, I suppose maybe make him notice the presence of the comment (How), but i´m not really sure if this would work in all the cases.

- Remove the plural of pelles, ¨Rammaser a la pelle¨ is a french expression that´s mean to something abundant, here : Les feuilles mortes (The dead leaves), can be fixed by adding this expression, but it would be a lot more useful to found a format to detect plural or not.

- Actually make it warn that it’s conjugated as ¨rammassent¨ as they are multiples leaves.

**Comment by vkyfox** [comment]
Added rule to detect the "." instead of "?" as an error in "comment allez-vous." With that 9 out of the 9 errors are detected.
