### ISSUE TITLE
Portuguese feedback "Evidência"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1623]
User feedback: "Evidência tem um assento circunflexo que sua aplicação não conseguiu detectar."

**Comment by qgustavor** [comment]
Existe as duas palavras: o substantivo "evidência", com acento, e o verbo "evidencia", sem acento. https://www.dicionarioinformal.com.br/diferenca-entre/evidencia/evid%C3%AAncias/ Sugere uma forma da aplicação detectar quando o verbo é usado no lugar do substantivo?

**Comment by Konfekt** [comment]
Exactly, you can enable checking by the rule `ACCENTUATION_CHECK_PT`.

**Comment by Konfekt** [comment]
It serves me well since its commit, but If I recall correctly its author prefers it to be disabled by default because of false positives.

**Comment by TiagoSantos81** [comment]
As @konfekt referred, there is a rule that has increased detection rates, although it as a false positive rate that is above my standards. 
I am closing this issue as is, since the report is false, but I would appreciate if it is reopened with the sentences that produce this false negative on that user.

**Comment by Konfekt** [comment]
Yes, I could not find  the rule`ACCENTUATION_CHECK_PT` anymore. How is the  new one called?

By the way, if you happen to use Vim, perhaps you find https://github.com/Konfekt/vim-langtool useful.

**Comment by TiagoSantos81** [comment]
Hi @Konfekt 

I haven't rechecked the code, nor used the use since we worked on it, but the 4.7 SNAPSHOTS still ships with the databases and PortugueseAccentuationCheckRule.java as well as PortugueseAccentuationDataLoader.java.
As far as I know, there where no changes to the the rule ID, but I will have a look at it in the coming days.

> By the way, if you happen to use Vim, perhaps you find https://github.com/Konfekt/vim-langtool useful.
At the moment, I don't use it, but I might in the future. Added to my bookmarks. Thank you.
