### ISSUE TITLE
How to handle placeholder in formatting string?

### ISSUE THREAD

**Issue by gosp** [languagetool-org/languagetool#1644]
For example:  `Hello, %1$s! You have %2$d new messages.`
The sentence is from android project, `%1$s` and `%2$d` are placeholder for formatting.

I try to modify `disambiguation.xml`, it doesn't work.
org\languagetool\resource\en\disambiguation.xml
```
    <rule id="ANDROID_RESOURCE" name="android string placeholder">
        <pattern>
            <token regexp="yes">%\d+\$s</token>
        </pattern>
        <disambig postag="NNS"/>
    </rule>
```
The issue is always: `The currency mark is usually put at the beginning of the number: $1. `

The workaround way is to use MARKUP API,  but it would cause other issues, like:
https://github.com/languagetool-org/languagetool/issues/1361

**Comment by MikeUnwalla** [comment]
>  it doesn't work.

`%1$s!` gets the postag NNS. But, there is no exception for NNS in the rule (CURRENCY) that causes the false positive.

As an alternative to adding a postag, could you put an antipattern on the rule (CURRENCY) that causes the false positive?

If you decide to use postags in disambiguation, I suggest that you don't use NNS (plural noun), because the text is not a plural noun. You could (I think) use SYM (symbol), despite tagset.txt saying "SYM   Symbol: not used by LanguageTool".

**Comment by gosp** [comment]
There isn't `CURRENCY` rule in `org\languagetool\resource\en\disambiguation.xml`. Should I add it firstly?
