### ISSUE TITLE
[en] PLURAL_VERB_AFTER_THIS false alarm

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1645]
> I think this commit should be moved to open-source.

Maybe the word "commit" is not detected as a noun?

![Bildschirmfoto 2019-06-20 um 08 34 28](https://user-images.githubusercontent.com/37363/59826317-60057c00-9336-11e9-8298-1a62de9d743e.png)

**Comment by MikeUnwalla** [comment]
Not a false alarm. In standard English, 'commit' is not a noun.

This problem of verbs being used as nouns occurs with other rules (example A_INFINITIVE).

In the pattern 'this + X + should', X is a noun. If we disambiguate it such that it IS a noun, then possibly, we will not find real errors.

A possible solution is to add a note to the message as I did yesterday in (https://github.com/languagetool-org/languagetool/commit/b4383e11e7aaa2ba10be0d02cd025da3840c49db): " Note: This error message can occur if you use a verb as a noun, and the word is not a noun in standard English."

Possibly, we should create grammar rules that find 'developer speak'.

**Comment by Discostu36** [comment]
I don't think we should only allow standard English in the POS dictionary. Because this way, we mask other possible errors like "I've contributed two commit to the repository."

I think the best (and most complicated)  solution would be to add `commit/S` to added.txt and additionally write a rule that tells the user that "commit" is not used as a noun in standard English.

**Comment by tiff** [comment]
@MikeUnwalla @Discostu36 Actually Wiktionary lists "commit" as a noun:
https://en.wiktionary.org/wiki/commit#Noun

**Comment by MikeUnwalla** [comment]
@tiff, yes "In computer science and data management,"

In some specialist subjects, words are used in a non-standard way. For example, I have seen the verb 'compute' used as a noun or an adjective, as in, "These compute resources are..." (Parse as a noun in a noun cluster or as an adjective that modifies 'resources'.)

Before we make changes, we should answer these questions:

- How do we decide which terms (verbs used as nouns) to include and which to exclude?
- If we allow verbs used as nouns, then should we also allow common nouns and proper nouns that are used as verbs? (As in, "If you LanguageTool your document, you will probably find many grammar errors.") If no, why not? (Because we already allow "If you google, you will find the information.")
- What is the best way to deal with non-standard usage?
- How do we prevent false negatives for the users who use a term incorrectly (because they are not using it with its specialist meaning)?

@Discostu36 wrote:

> I don't think we should only allow standard English in the POS dictionary. Because this way, we mask other possible errors like "I've contributed two commit to the repository."

In standard English, CD + VB does not occur. What is missing is a grammar rule that finds CD + VB ('two commit' in your example).

I am not against adding specialist terms to LT. I am against doing it without thinking about all the implications. I think that to do the job properly will be a lot of work (and thus, if we do it, we could possibly do it in LT Premium).

**Comment by tiff** [comment]
I think we should add terms when they are often used (we can see this when users add it to their dictionary often) and when the word has a proper entry at Wiktionary. Many LT users have a technical background and rely on us.

**Comment by tiff** [comment]
I have added `NN` and `NNS` POS tags for `commit` and `commits`
