### ISSUE TITLE
[pt] user feedback: "a gente" vs "agente"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1685]
> A correção em alguns momentos junta 2 palavras distintas como se tentasse abreviar e sugere por exemplo: agente por "connosco" que está incorreta. 

From a user of our Browser Plugin. Not sure what exactly he means.

**Comment by hsantanna** [comment]
First, the claim says that after grammar correction the user are getting two distinct words put together as if this two words was only one word, and the user perceive that as if the correction was trying to abbreviate the word, but the user doesn't report any way to reproduce that.

As another claim, the user also says that the grammar check is wrongly suggesting that the word "agente" should be changed to "conosco".

In portuguese "agente" means "agent" and "conosco" means "with us"/"about us"/or something like that. And if the claim could be confirmed, the grammar check is probably misleading the expression "a gente" (means "we"/"us") with the word "agente".

I didn't tested that myself, I'm just trying to clarify the initial claim, since I'm native on Brazilian portuguese.

**Comment by TiagoSantos81** [comment]
`a gente` is a very informal way to say `connosco`. Should not appear in written text, unless it is quoting someone. Therefore, the correction suggests that it is either a loose space when typing "agente" (same as English agent), or it should be replaced by "nós" ou "connosco".
