### ISSUE TITLE
[en] No suggestion for DID_BASEFORM

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1738]
> He didn't mistyped it.

There's a verb missing in the description of the error.
![Bildschirmfoto 2019-07-23 um 07 40 24](https://user-images.githubusercontent.com/37363/61685476-2d77e600-ad1d-11e9-85e3-d37aa1355e4f.png)

**Comment by MikeUnwalla** [comment]
@tiff, DOESNT_WITH_WRONG_VERB_FORM is in grammar-premium.xml, which overlaps the open-source rule DID_BASEFORM. The problem occurs with both rules. My understanding is that the problem occurs because the postags for 'mistyped' are in added.txt (refer to #844 and #1188).

I could remove 'mistyped' from the rule, but I don't think that that is a good solution.

**Comment by tiff** [comment]
Ah thx for clarifying

**Comment by MikeUnwalla** [comment]
2019-08-05: problem does not occur now.
