### ISSUE TITLE
StringIndexOutOfBoundsException crash with soft hypen

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1769]
See this in `MorfologikAmericanSpellerRuleTest`:

```
  @Test
  public void testBug() throws IOException {
    lt.check("sus\u00AD tainability");
  }
```

crashes with: 

```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 17
	at java.lang.String.substring(String.java:1963)
	at org.languagetool.JLanguageTool.adjustRuleMatchPos(JLanguageTool.java:897)
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1321)
```

Somehow caused by `ruleMatch.setOffsetPosition(ruleMatch.getFromPos(), ruleMatch.getToPos()+hiddenCharOffset);` in `MorfologikSpellerRule`. Seems https://github.com/languagetool-org/languagetool/commit/08e2ece63fd640e12e16bb344857abe6b3496bd3 and https://github.com/languagetool-org/languagetool/commit/0f85901b75ef64a66af0c44c05d630397b526c6e in combination cause this.

**Comment by danielnaber** [comment]
@arysin Any idea? Could you explain your "Make adjustments when handling ignored characters" change a bit?

**Comment by arysin** [comment]
@danielnaber Will take a look a bit later today

**Comment by arysin** [comment]
@danielnaber I've added a test code in testIgnoredChars() to show how 08e2ece fixes from/to positioning (without the fix the positions will be 0-3 and 4-15). Note this test code does not activate new fiture to merge misspelled words so it's not crashing.
I've also added a check for positions in testBug() - with 08e2ece reverted the test does not throw an exception but "to" position is off (15 instead of 16).
I'll try to see if I can figure out how to adjust spelling word merge but it may take some time for me to get into its logic.

**Comment by arysin** [comment]
So before the speller rule only operated on single token and with ignored characters hidden so we had to adjust "to" position later. With new code the speller operates multiple tokens and calculates "to" position differently.
I've added a check to skip adjustment for 2nd case. It may not be perfect so feel free to reopen if it happens again.
