### ISSUE TITLE
don't store binary files in git

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#200]
Our git repo is currently 323 MB in size. As we check in binary files, it will keep growing. In the long run, we will probably need to find a way to keep the versioned binary files out of git. Possible solutions (which unfortunately make the workflow more complicated):
- https://github.com/jedbrown/git-fat
- http://git-annex.branchable.com/

**Comment by danielnaber** [comment]
Current repo size: 387MB (`du -h` after a fresh clone)

**Comment by danielnaber** [comment]
Possible solution: Have a separate git module for the resources of each language, e.g. `resources-en` for the English resources. Every module contains a Maven project with the binary files. This project is specified as a dependency by the language, e.g. instead of containing the binary data itself, Maven project `language-en` will specify `resources-en` as a dependency. To make sure that developers always have the latest binary data, they either need to run `mvn install` in all resource projects, or they set up their Maven to get the  snapshot artifacts from Jenkins or Travis, who should build them anyway.

Note that by 'resources' I mean large binary files, not `grammar.xml` or `disambiguaton.xml`.

What's nice about this solution is that it isn't too complicated. Drawbacks:

* Does not really solve the problem forever, as it only moves the growth to the `resources-xy` repos.
* Developer must call `mvn install` in the resources project to test new dictionaries locally.
* http://github.com/languagetool-org/ will list another 30 modules, most of which are not interesting to contributors (as they only work in their own language).

There's another issue that could be solved by this: Every 3 months, we release artifacts to Maven central of which a lot binary hasn't changed (the unmaintained languages). Nobody has complained about it, but it's not really nice. This could be solved by only having a new release of the resources artifacts when it has actually changed (new dictionary etc.)

**Comment by danielnaber** [comment]
Git LFS might help: https://github.com/blog/1986-announcing-git-large-file-storage-lfs

**Comment by dpelle** [comment]
Daniel Naber <notifications@github.com> wrote:

> Git LFS might help:
> https://github.com/blog/1986-announcing-git-large-file-storage-lfs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/languagetool-org/languagetool/issues/200#issuecomment-91302062>
> .
>

My preference would be to build *all* binary dictionaries
by scripts.  So those big binaries that don't play well
with revision control would not need to be checked-in
anymore.

Regards
Dominique

**Comment by danielnaber** [comment]
Current repo size: 418MB (`du -h` after a fresh clone)

**Comment by pminos** [comment]
Hello, 

I am planning to use a real POS (and Synthesizer) dictionary for the Greek language, but I would prefer to publish it as an independent jar and add it as dependency for the following reasons

* space limitation of the languagetool repository
* re-usability

My intention is to have only the text version of the dictionary inside the source and build the binary files (FSA) using a maven plugin.

The final jar (that I will upload to the Central Repository) will contain only the binary files (FSA) and there will be no need for the rest of the developers to rebuild the dictionary.

Do you think any reason for not following this approach?

Regards,
Panos

**Comment by danielnaber** [comment]
Hi Panos, that's a good approach. We do this already for jwordsplitter for German.

**Comment by reckart** [comment]
Re-use is great ;) Please keep in mind to store resource within proper packages in the JAR according to the Java conventions (e.g. "org/your/resource/datafile") instead of just dumping it to the JAR root or to some random folder (e.g. "data") to avoid potential clashes with resource from other people.

**Comment by danielnaber** [comment]
Current repo size: 433MB (du -h after a fresh clone)

**Comment by arysin** [comment]
I have created a github project that generates Ukrainian dictionary from
source (words + affix rules) files.
And I am also willing to try this approach to provide FSA dictionaries for
Ukrainian via separate maven dependency.

Regards,
Andriy

2015-07-05 18:57 GMT-04:00 Panagiotis Minos <notifications@github.com>:

**Comment by danielnaber** [comment]
Andriy, that sounds great. Once you get it working, we should be able to use the same approach for more languages.

**Comment by arysin** [comment]
Hey Daniel

I've created a project (languagetool-dict-uk) to generate a jar with
Ukrainian dictionaries for LT in it in maven repo (it's a gradle project
but it should be easy to create maven one if needed). I talked a bit with
Marcin and Dawid who maintain morfologik project and it looks like we may
want to create thise dictionary jars under org.languagetool group as the
dictionaries we have a quite LT-specific and may have different licensing.
I am getting pretty close to make it work but I just realized that while
creating speller dictionary I am using
org.languagetool.dev.SpellDictionaryBuilder (to add frequency info) which
is not present in maven repo. It looks like this class is built in
languagetool-standalone which does not have a jar in central maven repo. It
would be nice if the proejct that creates the dictionary could pull that
dev class from maven. Shall we create something like languagetool-dev or
languagetool-tools/utils?

Thanks
Andriy

2015-11-05 16:38 GMT-05:00 Daniel Naber <notifications@github.com>:

**Comment by danielnaber** [comment]
We already have a languagetool-dev project in Maven, so we could just release it next time (after some cleanup), i.e. with LT 3.2 on 2015-12-20. What do you think?

**Comment by arysin** [comment]
That would work, the only problem I see with current languagetool-dev is
that it depends on language-all. Which means to pull a util class to
generate new spelling dictionary for some language I need to pull packages
for all existing LT languages.
It's probably not critical but if it's not too hard we may want to make the
package for creating dictionaries more independent: ideally only depending
on languagetool-core.

Thanks
Andriy

2015-11-21 5:18 GMT-05:00 Daniel Naber <notifications@github.com>:

**Comment by arysin** [comment]
Hmm, interestingly as of now org.languagetool.dev.SpellDictionaryBuilder is
not packaged into languagetool-dev, this class (as well as other builders
from dev/) is only present in languagetool.jar in languagetool-standalone...

So we would need to:
1) move those builders to languagetool-dev
2) remove language-all dependencies from languagetool-dev

Other than that I have a solution that works for Ukrainain dictionary and
that (after I do some cleanup) we can reuse for other languages.

Andriy

2015-11-21 10:28 GMT-05:00 Andriy Rysin <arysin@gmail.com>:

**Comment by arysin** [comment]
I did play with languagetool-dev and it seems like it has some code for
analysis which requires languages and thus pulls lots of dependencies which
is overkill if you're just trying to create a dictionary.
I would like to propose new module: languagetool-tools which purpose will
be only to assist in creating dictionaries (or other artifacts needed by
LT), this will be parallel to morfologik-tools which has similar purpose.

We'll move these files from languagetool-standalone to languagetool-tools:
DictionaryBuilder.java
DictionaryExporter.java
POSDictionaryBuilder.java
SpellDictionaryBuilder.java
SynthDictionaryBuilder.java

and the main dependencies will be languagetool-core and morfologik-tools.

The new pom is attached. If there no objections I can push this new module
today.

Two other aspects:
1) we can also make languagetool-standalone to depend on langaugetool-tools
in case there is some code out there relying on languagetool-standalone to
provide those builders
2) if 1) is not an issue we can move those files above in
org.languagetool.tools package to note they are not just for research (like
other .dev classes are) but for building core LT infrustructure and thus
may need to have more rigid API

Thanks
Andriy

2015-11-21 12:49 GMT-05:00 Andriy Rysin <arysin@gmail.com>:

**Comment by arysin** [comment]
One more "little" thing :)
Currently the *Builder classes from dev have runtime dependency on
language-<lang> module when building a dictionary for <lang>. It is fairly
easy to add runtime language-<lang> dependency when building a dictionary
in our new languagetool-dict-<lang> package (and it kinda works). But then
we have a circular dependency: language-<lang> depends on
languagetool-dict-<lang> and languagetool-dict-<lang> have a (runtime)
dependency on language-<lang> to build a dictionary. I don't think circular
dependencies like this is a good thing so I looked and
SpellDictionaryBuilder uses language-<lang> module only for two purposes:
1) to get a short language name for dictionary
2) to create word tokenizer for given language

For 1) we already pass a language code in parameters and for 2) we take a
word list (assumed 1 per line like hunspell's unmunch will generate) so we
don't really need a tokenizer.
So we could get rid of these circular dependencies by using language code
from parameters and assuming 1 word per line in the input file.

Andriy


2015-11-22 11:38 GMT-05:00 Andriy Rysin <arysin@gmail.com>:

**Comment by danielnaber** [comment]
I think the idea of `languagetool-tools` is a good one. `SpellDictionaryBuilder` could be moved to a tools package, we just need to update http://wiki.languagetool.org/hunspell-support#toc3. About the tokenizer: there were some special cases which I don't remember exactly, probably in German or English. But let's try without the tokenizer.

**Comment by arysin** [comment]
I've pushed new module languagetool-tools, here's quick summary:
1) it only contains classes for creating and exporting dictionaries
2) it only depends on langaugetool-core and morfologik-tools (although now
I am thinking it can only depend on morfologik-tools, but this module being
part of LT not sure if that makes sense)
3) I changed the invocation parameters to be name-based instead of position
based, I also used apache cli package to handle invocation parameters (this
allows to also reuse them and their description)
4) As I changed the parameters I did copy (not move) classes from
languagetool-standalone just in case somebody was using them (although we
can deprecate the old ones I guess)
5) I added (automated) unit tests on POS- and SynthDictionaryBuilder to do
some quick smoke-testing (will add a test for SpellDictionaryBuilder later)

Now those builders are used in dict_uk project to build Ukrainian
dictionaries for LT:
https://github.com/arysin/dict_uk/tree/master/distr/language-dict-uk

Some notes:
1) this is my first gradle project, hopefully it does not make people
looking at it puke :)
2) the gradle build looks into local maven repo for languagetool-tools
module
3) gradle file uses dictionary info files from src/resources/...
4) this build splits dictionary taks into prepare* and create*, first ones
use Unix commands to prepare the dictionary (change encoding, replace
spaces with tabs etc), second invokes *DictionaryBuilder class to actually
create the dictionary
5) I did make quick attempt to covert first part to groovy to make it
cross-platform but it got very verbose and *much* slower, so for now
preparing will stay with Unix commands; we could though embed this
"prepare" stage into *Builder classes at some point to make it a 1-step task
6) I did use "provided" configuration to provide classpath for JavaExec
task; alternative way would be to use buildScript{} block dependency and
invoke classes directly from the gradle build script
7) "gradle install" command will install language-dict-uk into local maven
repo

Then in my languagetool-language-modules/uk/pom.xml I added new dependency
"language-dict-uk" and then I removed binary dictionaries from uk/... and
when I build Ukrainian module it pulls them from the dependency rather than
them being included in git repo.

If this works we just need to figure out how to publish the dictionaries.
It would make sense to publish them under org.languagetool group but I am
not sure if repository has fine-grained permissions so we can allow each
language maintainer to push dependency up. Also I am not sure if it does
not complicate pushing LT release into repository unless Daniel can take
all current language-dict-* modules SNAPSHOT version and push them as a
release.

Also note that although dictionary releases in the repository are immutable
the snapshot versions can be updated between releases so if you pull the
sources from LT git for some time point in history between releases the
dictionary snapshot may be not right for the sources pulled (or may not be
even there? not sure if old snapshots are help in maven repo).


Andriy


2015-11-23 4:24 GMT-05:00 Daniel Naber <notifications@github.com>:

**Comment by danielnaber** [comment]
Thanks, some comments:

* Could you deprecate the old classes you copied?
* Could you add a copyright header to the new *.java files?
* I think `language-dict-uk` could be outside of languagetool if you do the releases, and it could be inside if the releases are always in sync with LT, i.e. one release every three months. Both seems okay.

**Comment by arysin** [comment]
Hi Daniel

I've did deprecate old classed and added copyright.

As for the releases: I think it makes a lot of sense for the package that
is only used by LT and provides resources in org/languagetool/
(sub)packages to be in org.languagetool group and thus be managed together
with LT. But that means I won't be able to push any LT changes between
releases that rely on dictionary update. So I guess if I need to update
dictionary more often than every 3 month I need to have it separately?
And if that's the case I have some questions:
1) can it (and should it) still be in org.languagetool group or that'll
have to be some other group? (org.languagetool.uk???)
2) right before new LT release do I need to release a stable version of the
dictionary as well (i.e. remove -SNAPSHOT and publish so LT can rely on
it)? and if I can't for some reason to do it on time, will it imactp LT
release?

Thanks
Andriy




2015-11-24 16:49 GMT-05:00 Daniel Naber <notifications@github.com>:

**Comment by danielnaber** [comment]
Here's an idea, but I'm not sure it works: during development, you work on the SNAPSHOT version and "release" it from time to time, i.e. make sure it's available somewhere (not on Maven Central, that only hosts releases). We change the pom.xml of LT so that it knows about the SNAPSHOT repo and gets your latest version from there. But you're right - before release, you have to make it a non-SNAPSHOT version, otherwise LT cannot be released. If that happened, we'd need to rollback the changes for uk and use the previous release of your module.

**Comment by arysin** [comment]
It looks like we can host dictionary snapshots here
https://oss.sonatype.org/content/repositories/snapshots/ (here's example of
the project doing this on every git push:
https://github.com/bumptech/glide/wiki/Snapshots)

But
1) I still don't fully understand if it can be the same group
(org.languagetool) or their security policy won't allow to have narrow
permissions for dictionary developers to only upload one package inside the
group and thus dictionaries should have each their own groups?
2) as you mentioned there's still problem with synchronization: when LT is
released the dictionary SNAPSHOT version will have to be changed to release
otherwise the whole language rolls back, this is just ugly for 1 dictionary
but for 25 it'll be IMHO unmanageable; potential solution could be to have
some automated process (script?) to create release packages for all
dictionaries (updated from last release) from their snapshot versions so it
can be run when LT is released (but then all those language pom.xml files
need to be updated before the release).

BTW even if we don't do dictionary snapshot versions, if new dictionary
version is released it should be deployed to the repository together with
new LT code that depend on it pushed in git. If only LT maintainer can
upload new release for the dictionary keeping dict and code in sync becomes
tricky (or LT maintainer publishes all new dictionaries first, then
dictionary developers push new code, then we make full LT release).

Alternatively we could look at git-lfs, it's not quite "git-clean" solution
but available on github and allows easy maintenance for keeping dictionary
and code in sync.

Andriy

2015-11-30 3:16 GMT-05:00 Daniel Naber <notifications@github.com>:

**Comment by danielnaber** [comment]
I cannot answer (1). About (2): well, we're quite far away from actually having 25 maintained dictionaries. The important point is maybe: is this dictionary package LT-specific or will there be other users outside of LT? If it's LT specific, we could continue as we do now or try git-lfs. If there are other users it makes sense to have it as an independent project, like all the other external libraries that LT uses. The maintainer is then responsible for making a new release every three months to get the latest version into LT.

**Comment by arysin** [comment]
So as I see it (and in the PoC I did) the dictionary package would provide
3 binary dictionaries (with .info files), I am not an expert on morfologik
but it looks that at least 2 dictionaries (synth and spell) out of 3 are
pretty LT-specific. More than that, all of them are packaged under
org/languagetool/. So I suspect the usage of such dictionary package would
be pretty much LT-only.

Andriy

2015-12-01 3:51 GMT-05:00 Daniel Naber <notifications@github.com>:

**Comment by pminos** [comment]
I wrote a maven plugin (https://github.com/pminos/morfologik-maven-plugin) for creating FSA dictionaries with morfologik-fsa. You can find a dummy example at https://github.com/pminos/morfologik-maven-plugin-example. This is the approach I plan to follow for the Greek dictionary.

This way we can handle the dictionary files as source code. The drawback is that the clean/build phase will need more time.

If you think it is useful, I can add support for spelling dictionaries (for now supports morphological and synthesizer dictionaries only). 

Panos

**Comment by arysin** [comment]
I just realized that languagetool-tools is not published on maven central
(at least my gradle script complains with
https://repo1.maven.org/maven2/org/languagetool/languagetool-tools/3.3/ not
found).
Shall we add that module so it's possible to build dictionaries with just
languagetool-tools dependency?

Thanks,
Andriy

2015-12-03 4:20 GMT-05:00 Panagiotis Minos <notifications@github.com>:

**Comment by danielnaber** [comment]
Yes, just add it to https://github.com/languagetool-org/languagetool/blob/master/languagetool-standalone/scripts/stage-artifacts.sh#L31so it becomes part of the next release

**Comment by arysin** [comment]
I thought about it a bit more and I guess if person is building an LT
dictionary the most probably reason is for LT development and LT sources
are then installed. Also if somebody is creating LT dictionary they most
likely want the very latest version of languagetool-tools so using dev
version is better than the last release anyway.

Regards,
Andriy

2016-05-08 4:11 GMT-04:00 Daniel Naber <notifications@github.com>:

**Comment by danielnaber** [comment]
git repo has grown to 1.2 GB (`du -h` after a fresh `git clone`)...

**Comment by danielnaber** [comment]
Closing, as most dicts have been moved to their own repo (like https://github.com/languagetool-org/french-pos-dict)
