### ISSUE TITLE
[nl] "Dat" marked as spelling error

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2012]
> Dat is afhankelijk van uw situatie

<img width="354" alt="Bildschirmfoto 2019-10-09 um 17 15 39" src="https://user-images.githubusercontent.com/37363/66494784-7d627f80-eab8-11e9-8e83-d77a88c3fee6.png">

**Comment by baarsrj** [comment]
I just noticed. (I do not get mails from Github because there are fat too much of those). 
I wanted to report it as a kind of bug.
In my database, Dat was recorded as a proper last name (which it is). No issues. When I removed it from the database, the removal was added to removed.txt automatically as Dat. Apperently, this not only blocks Dat in the middle of a sentence, but also at the start. Even when 'dat' is still in the ddictionary. I think that is not desired behaviour. Not for Dutch, not for any other language.

**Comment by danielnaber** [comment]
My understanding is that you say `removed.txt` is case-insensitive, but it shouldn't be. Is that correct?

**Comment by baarsrj** [comment]
I was mistaken. The issue is in prohibit.txt.
And I undderstand that 'dat' in prohibit.txt blocks 'dat' which is in the spelling liest; that is what the prohibit.txt is for. But I did not expect 'Dat' blocks 'Dat' as well as 'dat'. 
If that is the way it is meant to work, okay. But I am surprised.

I will just adjust my export software.

**Comment by tiff** [comment]
Seems fixed. Thanks!

**Comment by tiff** [comment]
@baarsrj I'm sorry but this still happens:
<img width="369" alt="Bildschirmfoto 2019-10-12 um 19 47 15" src="https://user-images.githubusercontent.com/37363/66705600-2fa07e00-ed29-11e9-927c-25e920d7069f.png">

**Comment by baarsrj** [comment]
Solved better.
