### ISSUE TITLE
[en] EN_DIACRITICS doesn't work anymore

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2051]
> The Pokemon game

Doesn't suggest: "Pokémon"

**Comment by danielnaber** [comment]
Change is live, now the problem remains that we suggest words not in the dictionary, e.g. "Pokémon". I'll discuss this with @MikeUnwalla later today.

All suggested words:
[suggested-by-diacritics-rule.txt](https://github.com/languagetool-org/languagetool/files/3761558/suggested-by-diacritics-rule.txt)

**Comment by danielnaber** [comment]
Agreed with Mike that he'll go over the list

**Comment by MikeUnwalla** [comment]
@danielnaber (and others),

If the diacritics rule suggests a term, then for all locales, LT should not give a spelling error.

For https://github.com/languagetool-org/languagetool/commit/12212d00bc38bec3af6e8e66aa15ebe139a713f3, I added the spellings to the general file. But, some terms are possibly locale-specific (example: brötchen, which I found on www.merriam-webster.com, but not on www.lexico.com or other non-AmE dictionaries.

So, what do we do?
* Move the [possible] locale-specific spellings to the applicable spelling file.
* Accept that a term with diacritics is correct in all locales.

**Comment by danielnaber** [comment]
> Accept that a term with diacritics is correct in all locales.

I'd say let's do that for now.

**Comment by MikeUnwalla** [comment]
@danielnaber, a 
The diacritics rule is applicable only to word pairs for which both spellings are correct (example Pokemon/Pokémon, cybercafe/ cybercafé). If only the diacritic word is correct, the rule is redundant, because the spell checker should find the error. We should do one of these:
* Put into comments (or remove) the pairs for which the non-diacritic term is a spelling error.
* Keep the pairs, but give the spell checker priority over the diacritic rule.
What do you think is the best option?

The rule is not always correct if a word with no diacritic is correct and has a different lemma to the word that has a diacritic. Some examples:
* chassé (dance step)/chasse (a liqueur) https://www.lexico.com/en/definition/chasse
* soufflé (food)/souffle ([medical term], rumbling sound) https://www.lexico.com/en/definition/souffle
* Provençal (an inhabitant of Provence, a language)/Provencal (town in USA) https://www.lexico.com/en/definition/provencal, https://en.wikipedia.org/wiki/Provencal,_Louisiana
* pliés (plural noun, ballet step)/plies (layers of a laminated material) [plurals and verb inflections are not yet in diacritics.txt]

Idea: use statistical methods to suggest diacritics:
Correct, no suggestion: Provencal is a village in Natchitoches Parish, Louisiana, United States.
Incorrect, suggestion: Provençal is a Romance language closely related to French.
Correct, no suggestion: The chassis was a typical composite ‘sandwich’ with inner and outer skins made up of woven laminated plies.
Incorrect, suggestion: The ballerina performed the plies perfectly.

I propose to put into comments the pairs of terms for which the non-diacritic term and the diacritic term have (or can have) different lemmas. Is that OK?

Diacritics.txt does not have entries for plurals or verb inflections. Should I add plurals and verb inflections?

**Comment by danielnaber** [comment]
> If only the diacritic word is correct, the rule is redundant,

Well, the user would get a more specific error at least.

I tried the ngram approach but it didn't work well. Maybe not enough data or these spellings are mixed up in our data.

> I propose to put into comments the pairs of terms for which the non-diacritic term and the diacritic term have (or can have) different lemmas. Is that OK?
> Diacritics.txt does not have entries for plurals or verb inflections. Should I add plurals and verb inflections?

Yes, please

**Comment by MikeUnwalla** [comment]
I have completed the assigned tasks.

For the record, here are my notes:
[1-word-common-noun-suggested-by-diacritics-rule.txt](https://github.com/languagetool-org/languagetool/files/3820179/1-word-common-noun-suggested-by-diacritics-rule.txt)
[1-word-proper-noun-suggested-by-diacritics-rule.txt](https://github.com/languagetool-org/languagetool/files/3820180/1-word-proper-noun-suggested-by-diacritics-rule.txt)
[multi-word-suggested-by-diacritics-rule.txt](https://github.com/languagetool-org/languagetool/files/3820184/multi-word-suggested-by-diacritics-rule.txt)

Additional tasks that could be done:
* Add POS for multi-word terms
* Check the POS/spelling of terms that do not have diacritics, but for which my notes say that the term without diacritic is possible
* Add coherency pairs.

@danielnaber , let me know if you want me to do one or more of those tasks.

**Comment by danielnaber** [comment]
> let me know if you want me to do one or more of those tasks.

So coherency pairs would be added for which words, only those where we accept both spellings and don't complain?

**Comment by MikeUnwalla** [comment]
> So coherency pairs would be added for which words, only those where we accept both spellings and don't complain?

Yes. The coherency pairs would be for words such as cafe/café which are both correct. (The diacritics rule says use 'café'.)

**Comment by danielnaber** [comment]
But if it's in the diacritics rule, why have it in coherency, too? Just in case someone ignores the diacritics rule and uses both variants in one text?

**Comment by MikeUnwalla** [comment]
>  Just in case someone ignores the diacritics rule 

Yes. Because 'cafe' (no diacritic) is correct.

It's not likely that someone will write café unintentionally. But, if you are an editor or a tech writer, and you compile texts from many sources, then it's possible for both forms to be in your text.
