### ISSUE TITLE
[es] "estas"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2085]
Feedback from a user:
> In Spanish, the word "estas" (demonstrative pronoun) is not corrected to "estás" (verb). And interrogative pronouns (Qué, Cuándo, Quién, etc.) are not marked as wrong when without the accent mark.

Probably related to https://github.com/languagetool-org/languagetool/issues/1876

**Comment by jaumeortola** [comment]
"Estas" and "estás" are both very common words. The same is true for que/qué, cuando/cuándo, etc. Specific rules will be needed, and they could be quite complex.

**Comment by tiff** [comment]
Thanks for clarifying @jaumeortola

**Comment by danielnaber** [comment]
I just tried adding confusion rules, but they don't work too well:

estas; estás: p=0.981, r=0.335
que;qué: p=0.985, r=0.340
cuando/cuándo: p=0.917, r=0.135

In other languages, we usually strive for a precision (`p`) of at least 0.99. So only cuando/cuándo would work there and with very low recall (`r`, i.e. it doesn't really find many matches). Of course, this could be due to errors in the evaluation data. Actually, I will re-run the test now with better data.

**Comment by danielnaber** [comment]
New results not that much better...

```
estas; estás; 10000000000;     # p=0.986, r=0.393
que; qué; 10000000000;         # p=0.988, r=0.434
cuando; cuándo; 10000000000;   # p=0.933, r=0.134
```

**Comment by jaumeortola** [comment]
The issue with estas/estás is more or less fixed (probably there is room for improvement). 
Some simple rules can be written for que/qué, quien/quién, etc., for example in questions:
`¿Quien es? > ¿Quién es?`
