### ISSUE TITLE
[fr] Bad typo error for conjugation error "s'assoupir"

### ISSUE THREAD

**Issue by maxiplay** [languagetool-org/languagetool#2196]
Épuisée, elle _s’assoupie_ doucement. 

should be 

Épuisée, elle s’assoupit doucement.

But language tool say : "Faute de frappe possible trouvée" and suggest  "elles ’assoupie". The suggestion is completely wrong and not French.

**Comment by vkyfox** [comment]
The error seems to come from a white space check : in "Elle s'assoupie," "s'assoupie" does not exist; whereas "Elles assoupie" are two existing words (even though grammatically nonsensical).

A solution for the white space checker would be to ignore a white space check where there is an apostrophe as no word can begin with an apostrophe.

**Comment by dpelle** [comment]
LT is correct.
"Elle s'assoupie" is not correct. Correct would be "Elle s'assoupit". Also correct would be "Elle est assoupie".

See: https://leconjugueur.lefigaro.fr/conjugaison/verbe/assoupir.html

Now we could argue that LT should give a better suggestion, but that's another matter.

**Comment by danielnaber** [comment]
> Now we could argue that LT should give a better suggestion, but that's another matter.

I'll keep the issue open for that. Not suggesting words that start with the apostrophe would be a step in the right direction, as far as I understand.

**Comment by dpelle** [comment]
> Not suggesting words that start with the apostrophe would be a step in the
> right direction, as far as I understand.

Not sure why we can't suggest words with apostrophes.

For the incorrect "Elle s'asspoupie", LT should ideally suggest "Elle s'assoupit" but good suggestions can probably only be done with a grammar rule since it's about checking whether the verb verb is conjugated consistently with the pronoun "elle" and suggesting the flexion of the conjugated word that are OK/compatible with the pronoun "elle".

**Comment by danielnaber** [comment]
I meant words that *start* with an apostrophe, or are there examples of those?

**Comment by dpelle** [comment]
@danielnaber  wrote:

> I meant words that start with an apostrophe, or are there examples of those?

The apostrophe is there because the French word *se* before a vowel is written as *s'* (e.g. s'assoupit). Similarly, those words also change before a vowel: le → l',  la → l', ne → n', de → d, que → qu', etc.

A good spell checker is able detect inconsistencies. In fact, the French Hunspell dictionary from Dicollecte (used in LanguageTool) does have all valid flexions for the verb "assoupir" and so it knows that "s'assoupit" correct, whereas "s'assoupie" is incorrect. See the 245 possible flexions of the verb "assoupir" in Dicollecte here:

https://grammalecte.net/entry.php?prj=fr&id=129550&fd=2

But what Hunspell is unable to do, is to propose logical suggestions based on the context.  The fact the the pronoun "elle" is used means that the correct suggestion is "elle s'assoupit.". If pronouns was "elles", correct suggestion would then be "elles s'assoupient". Clearly we can only propose such suggestions with a grammar rule and not the spelling checker alone.

**Comment by jaumeortola** [comment]
> Elle s’assoupie -> s'assoupit

Solved with the new rule PRONSUJ_NONVERBE
