### ISSUE TITLE
[fr] spelling.txt not used for generating suggestions?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2229]
The French spelling.txt contains "WordPress" but it's not showing in the suggestions:
![Bildschirmfoto 2019-12-17 um 12 52 28](https://user-images.githubusercontent.com/37363/70993363-27b7de00-20cc-11ea-865a-1fe7387e948b.png)

Probably related to https://github.com/languagetool-org/languagetool/issues/2010 @danielnaber

**Comment by tiff** [comment]
Same happens for "Iphone"

![Bildschirmfoto 2019-12-17 um 15 05 20](https://user-images.githubusercontent.com/37363/71002001-b5042e00-20de-11ea-93b0-a0e422eb8db3.png)

**Comment by danielnaber** [comment]
work in progress update:

* I think we cannot add words to a binary dictionary programmatically, so we have two spellers (binary and plain text) whose results we simply append (see #2010)
* To mix the results in a more clever way would mean we implement parts of morfologik, considering frequency and/or edit distance
* `speller.getFrequency(word)` might help to re-sort the list, but that always returns 0 for some unknown reason
* Proper solution: re-sort all results using a good language model.
* Quick fix is *not* to just ignore case, as that would get us "CA" or "cA" as top suggestions instead of "Ça" (see `FrenchCompoundAwareHunspellRuleTest`)
* Idea: use `Speller.CandidateData` - it's public and it considers the frequency
