### ISSUE TITLE
[br-FR]A few hyphen rules for breton LanguageTool

### ISSUE THREAD

**Issue by Wanibzh29** [languagetool-org/languagetool#2300]
Hello,
You will find ~4000 new rules for LT-br-FR.
[A few hyphen rules for breton LanguageTool.zip](https://github.com/languagetool-org/languagetool/files/4026416/A.few.hyphen.rules.for.breton.LanguageTool.zip)

**Comment by jimregan** [comment]
Hi.
It looks like these are all phrases that should be written hyphenated - in some language modules, we use a Java rule for this: if you could translate that, it would be more efficient than redoing all of these in XML. 
The translatable parts start here: https://github.com/languagetool-org/languagetool/blob/2c064fcdadcdaae6d473558a5ddbebb6ab0b9ee3/languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/CompoundRule.java#L53
That done, you would just need a text file like this:
[compounds.txt](https://github.com/languagetool-org/languagetool/files/4027654/compounds.txt)

**Comment by dpelle** [comment]
Yes, a Java rule would be more efficient for sure.

I glanced at the the list in the attached file. I don't think we can blindly use the list unfortunately. Several of the items in the list can be valid with or without an hyphen, with different meanings.

Example:
* merc'h-vihan = grand-daughter
* merc'h vihan = short girl

So if we'd use the list as-is, it would give false errors. I want to avoid false errors as much as possible because users tend to lose trust and give up when there are many false errors.

So instead we need a list where the combination of words is only valid with an hyphen (or extremely unlikely without hyphen). My Breton not good enough to tell which words should always be separated by an hyphen in this list.

**Comment by Wanibzh29** [comment]
Hello,
Firstly @jimregan you will find the transtalions done below:
            "Skrivet e vez ar ger-mañ boaz gant ur varrennig-stagañ.", 
            "Ar ger-mañ a zo skrivet boaz evel unan hepken.", 
            "An droienn-mañ a zo skrivet evel ur ger hepken pe gant ur varrennig-stagañ.",
            "Kudenn barrennig-stagañ");
    addExamplePair(Example.wrong("Gwelet em eus un <marker>alc'hweder gwez</marker> e-kerzh an dibenn-sizhun-mañ."),
                   Example.fixed("Gwelet em eus un <marker>alc'hweder-gwez</marker> e-kerzh an dibenn-sizhun-mañ.."));

@dpelle You are totally right I will re-send a list in a few days saying which items could be written with an hyphen and also without. I haven't seen it before. 
For doing this job I have re-used a list of all the datas given to me by the Public Office for the Breton Language coming from the website: http://meurgorf.brezhoneg.bzh.
Regards

**Comment by Wanibzh29** [comment]
Hi, @TiagoSantos81 and thank you for all you are doing.

**Comment by Wanibzh29** [comment]
Hello,
You will find the new version of the compounds-br.txt.
Nice day :D
[compounds-br.txt](https://github.com/languagetool-org/languagetool/files/4034924/compounds-br.txt)
