### ISSUE TITLE
[ru] "Экслюзивы"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2314]
User feedback:
> Серьезно, без буквы "ё" программа слова уже не распознает? А множественное число -- уйма слов, которые резко оказываются ошибка, просто потому что написаны в множественном числе. Экслюзивы, тому пример.

**Comment by jimregan** [comment]
This is two things: 
1. complaining that a word is flagged as a spelling mistake because the letter 'ё' is missing, 
2. pointing out that plural forms of words are missing from suggestions, e.g., 'Экслюзивы' (-> 'Эксклюзивы')
With 1., it at least used to be a thing that the ispell or aspell dictionary for Russian came in a 'yo' and 'no-yo' version.

**Comment by yakovru** [comment]
Слово "эксклюзивы" добавлено.
Слова без буквы "ё" - это однозначно ошибка!!! Даже в книжных текстах, изданных после 1956 года, где буква "ё" последовательно не употребляется, всё равно в некоторых случаях эта буква должна быть проставлена! Возможным выходом для этого является создание специальной локали без буквы "ё" - issue #454
Word "эксклюзивы" and it forms has been added.
Words without the letter "ё" are issue #454
