### ISSUE TITLE
[en] wrong tagging of "vote" VB

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2328]
> I couldn't vote because nothing applied to me.

"vote" is only tagged as NN:UN

**Comment by tiff** [comment]
Another one (where figure is NNP):
> It would be nice if I could figure a way.

And one more (reference is NN:UN): 
> Do you have contact info or a case number we can reference?

**Comment by tiff** [comment]
> I have a mandolin lesson at 11am on Saturday, which I can't miss because Tom is teaching me less these days.

"miss" is tagged as "NN:UN"

**Comment by tiff** [comment]
> I can`t power off or on or dimming it.

power = NN:UN

**Comment by tiff** [comment]
> We will not know whether individuals have state filing obligations without seeing their detailed tax information

know = NN:UN

**Comment by MikeUnwalla** [comment]
- [ ] I couldn't vote because nothing applied to me. Caused by NN_CC_NN.
- [ ] It would be nice if I could figure a way. Caused by figure_1_NNP.
- [ ] Do you have contact info or a case number we can reference? Caused by E_NP_NN_VBP
- [ ] I have a mandolin lesson at 11am on Saturday, which I can't miss because Tom is teaching me less these days. Caused by NN_CC_NN
- [ ] I can`t power off or on or dimming it. Caused by E_NP_NN_VBP
- [ ] We will not know whether individuals have state filing obligations without seeing their detailed tax information. Caused by NN_CC_NN.

**Comment by MikeUnwalla** [comment]
My changes caused regression errors.
