### ISSUE TITLE
An empty correction and no correct example causes an incorrect suggestion

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#2352]
In a grammar file, if `correction="" ` and if there is no correct example, LT shows incorrect text as a 'correct' example.

![image](https://user-images.githubusercontent.com/5816160/72799469-351d3680-3c3d-11ea-8c85-132f0393cae1.png)

Testrules/Maven should do one of these:
* Give a warning that a 'correct' example is missing.
* Give a failure message.

**Comment by romele2** [comment]
Hello, 
I would like to work on this issue, I tried testing it a bit and I couldn't compile the program with an empty correction unless the <suggestion>  part was empty or absent, which makes me think the issue might have been mostly fixed. 

![Capture d’écran du 2023-04-07 11-37-02](https://user-images.githubusercontent.com/76474065/230587401-38b676ad-3ac2-472f-9cef-851a470184ed.png)

Should I perhaps make it so that an empty suggestion also fails ?

**Comment by MikeUnwalla** [comment]
@romele2, I closed this issue because the incorrect suggestion does not occur now: 
![image](https://user-images.githubusercontent.com/5816160/231077897-0c8dd55f-afc1-4d4d-89e3-de3432bb844d.png)

@languagetool-org/developers, LT does not find the error now.
