### ISSUE TITLE
pattern using min=0 fails

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#2553]
The pattern below fails.
```
<rule id="ERROR_DEMO1" name="" default="off">
  <pattern>
    <token>Wat</token>
    <token min="0">niet</token>
    <token postag_regexp="yes" postag="WKW:(VLT|TGW):1EP"/>
    <token postag="SENT_END"/>
  </pattern>
  <message>demo error</message>
  <example type="incorrect"><marker>Wat niet wist.</marker></example>
</rule>
```

**Comment by danielnaber** [comment]
I guess the problem is that `niet` matches both `<token>niet</token>` and `<token postag_regexp="yes" postag="WKW:(VLT|TGW):1EP"/>`, but we don't have proper backtracking, i.e. the result (matches vs. doesn't mach) depends on which matches first. To fix this, the rule matching would need to be rewritten so that it actually behaves like a regular expression engine (with backtracking).

**Comment by baarsrj** [comment]
In the case of 'niet', it can be circumvented by adding disambiguator rules, since 'niet' is hardly ever a noun. But this does not apply to the other bugs reported; this one I will close.
