### ISSUE TITLE
LibreOffice add-on: remote server doesn't work

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2642]
The public LT API server (https://languagetool.org/api) has a limit of - currently - 40 requests per minute. Thus, when using it with a text that's not quite short, the user gets:

![Bildschirmfoto von 2020-03-29 14-14-37](https://user-images.githubusercontent.com/857004/77848829-d5f11a80-71c7-11ea-9eac-d3db385c8130.png)

The user has no way to understand the actual cause, so I suggest removing the option that uses the public server. Using a private server is okay, as these can be configured without a limit.

**Comment by FredKruse** [comment]
@danielnaber I can't reproduce this issue. The limit of the server is retrieved at the beginning of check. The length of text is limited by the extension to the server limit. This problem is regarding only the text level rules. I tested the option with a document of 150 pages just now. It has been worked without any problem. Do you have a test case?

**Comment by danielnaber** [comment]
Indeed now I cannot reproduce it anymore.
