### ISSUE TITLE
[fr] "l’ONU"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2665]
I see many users adding "l’ONU" to their dictionary. What does it mean?

**Comment by tiff** [comment]
Found it myself, it's the French name for UNO: https://fr.wikipedia.org/wiki/Organisation_des_Nations_unies

**Comment by tiff** [comment]
Fixed through a disambiguation rule, not sure if this is the best approach:
https://github.com/languagetool-org/languagetool/blob/ef42703670f04c6cc186f7236aa96bf29affc416/languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/disambiguation.xml#L1822-L1830

The same issue also happens with "l'Harvard"

**Comment by jaumeortola** [comment]
There is "Onu" in the French tagger dictionary, but not "ONU". I think it should be added. 

The rule triggered seems to be this (premium rule?):
![imatge](https://user-images.githubusercontent.com/4289501/78252360-03550580-74f3-11ea-9f6a-350b20546678.png)

**Comment by dpelle** [comment]
@tiff wrote:

> Found it myself, it's the French name
> for UNO: https://fr.wikipedia.org/wiki/Organisation_des_Nations_unies

Yes, that's correct. The abbreviation is commonly used
and writing "l'ONU" should thus not trigger an error from
a user point of view.

@jaumeortola wrote:

>There is "Onu" in the French tagger dictionary, but
> not "ONU". I think it should be added.

Indeed, I see "Onu" in the dictionary. But I have no
idea what it is is.  I think it's a mistake in dicollecte,
or if it's a real word, it must be rare and most people
would not know what it is (at least I don't and I'm French).
It was most certainly meant to be "ONU" instead of "Onu".

Here is the suspicious entry in Dicollecte:
https://grammalecte.net/entry.php?prj=fr&id=125021

I've just proposed a change to Dicollecte:
https://grammalecte.net/proposition.php?prj=fr&id=29777

@tiff wrote:

> The same issue also happens with "l'Harvard"

No, it's not the same.  l'Harvard is incorrect in French
so signaling an error is good.

For many words with H (but not all of them) we should
never put the apostrophe e.g.  le hamster is correct
whereas l'hamster is incorrect.. That's not true for all words,
e.g. l'homme (the man) is correct, and not le homme is
incorrect.

Fortunately, dicollecte indicates whether to put apostrophe
or not.  For example:
* hamster has tag "s.":  https://grammalecte.net/entry.php?prj=fr&id=150189
  so Hunspell signals an error for the incorrect l'hamster  (dicollecte
  also shows that it's an allowed flexion).
* whereas homme has tag "s*": https://grammalecte.net/entry.php?prj=fr&id=150698
  so Hunspell allows  l'homme.

So it's fine here.
Besides, in the case of the word Harvard it would not make much
sense to put the article le or l' in front anyway.

**Comment by tiff** [comment]
@dpelle thank you!

Does the same apply to "d'Havard"? I got it from the Wikipedia page (https://fr.wikipedia.org/wiki/Universit%C3%A9_Harvard)

> Massachusetts Hall : le plus ancien bâtiment d'Harvard encore en place, il a été construit en 172013, il abrite aujourd'hui les bureaux des administrateurs de l'université, parmi lesquels son président ;

![Bildschirmfoto 2020-04-02 um 16 54 13](https://user-images.githubusercontent.com/37363/78263858-c7c23780-7502-11ea-971f-eb272028c354.png)

**Comment by dpelle** [comment]
@tiff asked:

> Does the same apply to "d'Havard"?

I see that for proper nouns, whether to use the apostrophe (élision)
or not is floating. It's not as clear as for regular words.

So I think we should allow both d’Harvard and de Harvard.
Looking at https://fr.wikipedia.org/wiki/Universit%C3%A9_Harvard I see both being used.

Some related links (in French) about élision and proper nouns:
* http://www.academie-francaise.fr/solene-o-france
* http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=3685
* https://www.question-orthographe.fr/question/elision-h-aspire-et-h-muet/

I'll see when I find time how it can be fixed in LT.

**Comment by tiff** [comment]
@dpelle thanks for the explanation

**Comment by dpelle** [comment]
I see that "Onu → ONU" is now fixed in dicollecte (see: https://grammalecte.net/proposition.php?prj=fr&id=29777 )

Of course, the fix will only land in LanguageTool when:
* there is a new release of Dicollecte
* and the new release is integrated in LanguageTool
So it can still take time.

**Comment by jaumeortola** [comment]
@dpelle Another similar issue in Dicollecte: Otan should be OTAN?

@tiff I see possible false alarms in the rule with the message "Un texte tout en majuscules peut être considéré intrusif (à moins que ce ne soient des acronymes)." For example, if you write "L'EDF", "L'ABC" or "L'ONU" (even after the dictionary change?). These can be fixed easily.

**Comment by tiff** [comment]
@jaumeortola ah I see. That rule is in premium. @danielnaber can you provide access to @jaumeortola, so he can fix it?

**Comment by dpelle** [comment]
Thanks @jaumeortola.

Change proposed in Dicollecte for Otan → OTAN : https://grammalecte.net/proposition.php?prj=fr&id=29779

Given that we found Otan and Onu, I would not be surprised if there are others like these.
