### ISSUE TITLE
[es] false alarms AGREEMENT_DET_NOUN?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2778]
@jaumeortola do we maybe have a wrong tagging on "COVID-19" / "coronavirus"?

![Bildschirmfoto 2020-04-21 um 09 43 00](https://user-images.githubusercontent.com/37363/79839272-8e1f7680-83b4-11ea-97c6-0d5b9c9a930f.png)

![Bildschirmfoto 2020-04-21 um 09 44 15](https://user-images.githubusercontent.com/37363/79839358-b313e980-83b4-11ea-854a-47d67478807b.png)

**Comment by tiff** [comment]
Also note the `el corona virus` (I guess we need a compound rule for that?)

**Comment by jaumeortola** [comment]
The recommended tagging of COVID-19 is feminine. But it is reasonable to relax it and accept both masculine and feminine. Or we could write a rule with more information.

The compound rule for "corona virus" already exists. But there is overlapping of different rules ("el corona"). It can be fixed.  

In the other sentences, there are errors in almost all of them. But the users are "impatient" and disable the rule because they don't get exactly the most adequate suggestion. The suggestions can be improved, but it needs more work.

**Comment by tiff** [comment]
@jaumeortola thanks. BTW. I will contact you on Slack over the next days to show you how you can access the data above yourself. :)

**Comment by jaumeortola** [comment]
Now, most of the sentences in the snapshot get the expected suggestion.
