### ISSUE TITLE
[fr] False alarm "par conséquent" + masculin suivi du féminin

### ISSUE THREAD

**Issue by bperel** [languagetool-org/languagetool#2852]
> Leur différence avec la série des vélaires simples est par conséquent perdu**e**.

LanguageTool suggests removing the "e" because:
> « conséquent » et « perdue » ne semblent pas bien accordés en genre.

which is incorrect because "par conséquent" is an expression that shouldn't be accorded.

**Comment by tiff** [comment]
@vkyfox the affected rule is ACCORD_GENRE (sub id 1)

**Comment by dpelle** [comment]
I'll fix it. The disambiguator should tag "par consequent" as adverb. 
https://en.wiktionary.org/wiki/par_cons%C3%A9quent#French

**Comment by dpelle** [comment]
Fixed in:
```
commit b5e8f576f32c12c9937f5474364aec256977711c
Author: Dominique Pelle <dominique.pelle@gmail.com>
Date:   Mon May 4 18:13:03 2020 +0200

    [fr] improved disambiguation of "par conséquent"
    
    This fixes false errors in rule ACCORD_GENRE and
    improves rule ETRE_VPPA_OU_ADJ. Fixes issue #2852.
```
Now all those cases are treated correctly:

**No errors**

Il est par conséquent perdu.
Elle est par conséquent perdue.
Ils sont par conséquent perdus.
Elles sont par conséquent perdues.

**Errors detected**

Il est par conséquent perdue.
Il est par conséquent perdus.
Il est par conséquent perdues.
Elle est par conséquent perdu.
Elle est par conséquent perdus.
Elle est par conséquent perdues.
Ils sont par conséquent perdu.
Ils sont par conséquent perdue.
Ils sont par conséquent perdues.

**Comment by tiff** [comment]
Great!
