### ISSUE TITLE
"He are good" is corrected, but "Mike are good" is not (English rules)

### ISSUE THREAD

**Issue by AngeloG** [languagetool-org/languagetool#287]
This sentence gets corrected by replacing `are` with `is`: "He are good", but replacing `He` with a name, such as `Mike`, does not get corrected, and passes as correct: "Mike are good".

Is this intentional?

**Comment by danielnaber** [comment]
`Mike` is a special case as it's also known as as verb (see https://en.wiktionary.org/wiki/mike) and we had excluded that, probably to avoid false alarms. I've extended the rule to work a bit better, with the next update (tonight on languagetool.org), at least cases like `Jim are good.` will be detected.

**Comment by Lowallyn** [comment]
Hello, I don't think that's the case because numerous times and other examples could be given with the same result.

 http://puu.sh/iPsBr/9e23887961.png <- within this screenshot nimble writer that uses LanguageTools is unable to detect the subject verb agreement, not being able to note the plurality (is being singular, and are plural). 

http://puu.sh/iPsMl/b25f527627.jpg on the LanguageTools site I inputted a similar sentence. same result. 

I don't know much about LanguageTools or programming but I was wondering if it was unable to recognize proper nouns. However when I used the pronouns 'He' and 'I' it had this result: http://puu.sh/iPt90/33bfaad36c.png
No problems detected either.

I hope this helps and thank you.

**Comment by danielnaber** [comment]
@Lowallyn The cases you cite are a different rule, which is based on chunks (http://wiki.languagetool.org/using-chunks). `Jim are good` is detected now and you can click on the error and select "Rule implementation..." to see what rule has been activated. Help with the chunk-based rule is welcome, but as it's a different issue I'll close this report.
