### ISSUE TITLE
[en] Discretize/Discretise show as spelling mistake

### ISSUE THREAD

**Issue by leodario7** [languagetool-org/languagetool#2872]
[en] Discretize/Discretise

`https://www.lexico.com/definition/discretize`
`https://en.wiktionary.org/wiki/discretize#English`

**Comment by MikeUnwalla** [comment]
@danielnaber,

There is a more general problem with some ~ise/~ize spellings. When I wrote the Oxford spelling rules for BrE (in category BRE_STYLE_OXFORD_SPELLING), if LT gave a spelling warning for ~ize, I added the word to spelling_en-GB.txt.

In most cases, the ~ize spelling is correct AmE. But, it is not necessarily correct for other variants of English.

"Unlike British English, which is split between -ise and -ize in words such as organise and realise, with -ize favoured by the Oxford English Dictionary and -ise listed as a variant, -ize is rare in Australian English and designated as a variant by the Macquarie Dictionary" (https://en.wikipedia.org/wiki/Australian_English#Spelling_and_style).

So, I am not sure of the best/optimum way to fix the problem.
1. Add discretize (and other ~ize that are AmE) to spelling_en-US.txt.
2. Add discretize (and other ~ize) to spelling.txt and remove it from spelling_en-GB.txt?

**Comment by danielnaber** [comment]
Mhh, I'm not sure either. How many ~ize words are there? Do we have more sources than just Wikipedia?

**Comment by MikeUnwalla** [comment]
There are 738 ~iz words (base form) in spelling_en-GB.txt. Not all are AmE (example: sulphurize). For AmE, a visual check shows that approximately half cause spelling errors in LT.

Probably, there are other sources than Wikipedia. It was the first one that I found in a Google search.

**Comment by danielnaber** [comment]
So my understanding is the ~ize forms will be complained about by a rule, except for en-GB? So if we add them to spelling.txt, they would be accepted by the spell checker, but there would be no rule to complain about them, as the rule is specific to en-GB?

**Comment by MikeUnwalla** [comment]
Not quite.

The ~iz rule for BrE finds ~is and says that Oxford recommends ~iz.

My question is about spelling warnings. How do we deal with ~iz words that are correct AmE and correct BrE, but are not necessarily correct in the other variants of English? Do I add the words to spelling_en-US.txt or to the general English spelling file (spelling.txt)?

I think I have just answered my question:
* If we know for sure that ~iz is possible in all variants, then, add the words to spelling.txt. There will still be exceptions such as 'sulphurize' which is not correct AmE and thus must be added to each locale if it gives a spelling error. That is out of scope of this issue.)
* If ~iz is not accepted in one or more locales, then for incorrect warnings, add the words to spelling_en-US.txt.

My next task: I will try to find whether ~iz is used on all the EN variants that LT supports.

**Comment by danielnaber** [comment]
Yes, sounds good.

**Comment by MikeUnwalla** [comment]
According to Wikipedial, these variants (ignoring BrE and AmE) of English that LT supports accept the ~ize spelling:

- Australian: Macquarie Dictionary "is generally considered by universities and the legal profession to be the authoritative source on Australian English... It gives -ise spellings first, listing -ize spellings as acceptable variants" (https://en.wikipedia.org/wiki/Macquarie_Dictionary).
- Canadian. "Words such as realize and paralyze are usually spelled with -ize or -yze rather than -ise or -yse" (https://en.wikipedia.org/wiki/Canadian_English#Orthography).
- New Zealand "In words that may be spelt with either an -ise or an -ize suffix (such as organise/organize) New Zealand English, like Australian English, mainly prefers -ise" (https://en.wikipedia.org/wiki/New_Zealand_English).
- South African. No reference found.

As an alternative method to find the permitted spellings, I put these words into LT (none of the words are in spelling.text):

Colonization
colonize
demonize
deodorize
energize
familiarize
finalize
generalization
generalize
itemize
nationalize
normalize
plagiarize
stabilize
stabilization

Results:
Australian English: all give spelling warnings
Canadian English: no spelling warnings
New Zealand English: one warning for 'demonize'
South African English: one warning for 'demonize'

Conclusion: if we accept that Australian English prefers ~ise, but that ~ize is also possible, then most of the ~ize terms that are in spelling_en-GB.txt should be in spelling.txt. (Terms such as 'sulphurize', must remain in spelling_en-GB.txt because they are incorrect AmE and possibly incorrect in other locales.)

@daniel, I propose to move most of the the ~ize terms from spelling_en-GB.tx to spelling.txt. Is that OK with you, or would you prefer me to copy them to spelling_en-US.txt?

**Comment by MikeUnwalla** [comment]
Process:
- Get all the ~iz base form from spelling_en-GB.txt.
- Paste into LT. For each AmE spelling error, if the word is not in www.merriam-webster.com, remove it. (Except for discretize, which is a technical term.)
- Add inflections for verbs. (I did not add inflections for nouns. Some nouns are countable, others are non-count, and the usage is different in different locales.)
- Add the words to spelling.txt.

@danielnaber , I have not removed the ~iz terms from spelling_en-GB.txt. (If we find that any spellings must be removed from spelling.txt, I will have to add them back to spelling_en-GB.txt. As best I know, there is no harm in leaving the words in spelling_en-GB.txt.) If you want me to remove the now redundant words from spelling_en-GB.txt, tell me.
