### ISSUE TITLE
[pt-br] False alarm of grammatical gender for "curinga" and "cara"

### ISSUE THREAD

**Issue by hmslima** [languagetool-org/languagetool#3021]
> O curinga.
> O cara.

<hr>

"_curinga_" is a masculine word. ([link](https://pt.wikipedia.org/wiki/Curinga_(baralho)))

<hr>

The word "_cara_" is a bit complicated. Its formal meaning ("_rosto_", i.e, "face") indeed is feminine, so theoretically LanguageTool is correct in suggesting "_a cara_", however "_cara_" may also mean "guy", so "_o cara_" means "the guy", although this word in this second meaning only occurs in informal speech. I suppose that LanguageTool has a policy of following only the formal language, but I want you to know that.

A cara = The face _(formal language)_
O cara = The guy _(informal language)_

**Comment by marcoagpinto** [comment]
@hmslima 

Hello!

"curinga" can be both male and female:
https://dicionario.priberam.org/curinga

Shall I add it to the morphologic dictionary as both (it is not in it)?

Regarding "cara", I noticed it months ago, but I am still not sure how to proceed about it since it can be easily mistaken with "face". So, one could accidentally use "o" when it meant "a".

@jaumeortola What is your opinion regarding "cara"?

**Comment by jaumeortola** [comment]
> Regarding "cara", I noticed it months ago, but I am still not sure how to proceed about it since it can be easily mistaken with "face". So, one could accidentally use "o" when it meant "a".

This kind of thing happens in other languages. There is no perfect solution. I would leave "cara" feminine. You can try to minimize false alarms with "cara (masc.)" if you find use patterns, but it will not be easy.

**Comment by marcoagpinto** [comment]
@jaumeortola 
Thank you!

@hmslima 
Regarding the "curinga", I have just added POS information:
https://github.com/languagetool-org/languagetool/commit/773d93d6221684ccfaff26b4173fbd9bbaf10a8e

It will be available in the nightly.
