### ISSUE TITLE
[en] false alarm DID_FOUND_AMBIGUOUS

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3090]
> Those flips you just did were on point.

![Bildschirmfoto 2020-06-15 um 13 01 05](https://user-images.githubusercontent.com/37363/84650325-49bddc00-af08-11ea-8e29-dffd533547ff.png)

**Comment by MikeUnwalla** [comment]
Also: 

> Those tests the technician actually did **found** the problem

**Comment by MikeUnwalla** [comment]
@tiff , 

I think the purpose of the rule is to show users possible semantic ambiguities (as with the found/find problem).

The entity `ambiguous_past_tense_forms` contains `found`. That makes sense to me. We have the verb 'found' (=to establish) and we have the past tense of 'find'.

The entity `ambiguous_past_tense_forms` also contains `babysat`. Why? There is no verb 'to babysat'. (This was discussed in https://forum.languagetool.org/t/en-did-you-found-find-it/4694). 

The rule finds:

> Sorry, I cannot **babysat** for you.

The rule does not find:

> Sorry, I cannot **cooked** for you. [DID_BASEFORM [1] finds the error.]

DID_BASEFORM does not find the 'babysat' error, because 'babysat' is missing a postag (VBD). (So, I will fix that.)

The entity `ambiguous_past_tense_forms` also contains `backlighted`. Why? There is no verb 'to backlighted'.

I propose to remove the terms in 'ambiguous_past_tense_forms' that are not also the base form of a verb. @tiff , do you agree?

**Comment by tiff** [comment]
Yes, feel free to do so.

**Comment by MikeUnwalla** [comment]
@tiff , the chanes fix the problem of "flips you did".

But, the rule triggers an error for this sentence:

> Those tests that the technician actually did **found** the problem.

If you think the FP is not worth worrying about, close the issue. If you want me to try to add an AP, let me know.

**Comment by MikeUnwalla** [comment]
Although there is a false positive with the sentence that follows, I am closing the issue because the message is "make sure..."

>Those tests that the technician actually did **found** the problem.

Feel free to re-open this issue if you don't agree.
