### ISSUE TITLE
LT add-on causes LibreOffice to crash upon opening some tables

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3112]
See https://forum.languagetool.org/t/lt-add-on-causes-libreoffice-to-crash-upon-opening-some-tables/5791

[Bilingual_index.xlf.docx](https://github.com/languagetool-org/languagetool/files/4793203/Bilingual_index.xlf.docx)

**Comment by FredKruse** [comment]
The file Bilingual_index.xlf.docx is very special. I was not able to create a similar file using LO. It contains only a table and no normal text, not even an empty row. LT assumes there is at least one row of normal text. LO doesn't handle this case in the used interface. Now, I wrote a workaround, so that files like this will be handled by LT without a crash.
Please test it tomorrow and close the issue.

**Comment by FredKruse** [comment]
The bug is fixed, I close the issue
