### ISSUE TITLE
NullPointerException in LibreOffice add-on

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3146]
I get this error...

![Bildschirmfoto von 2020-06-22 16-38-28](https://user-images.githubusercontent.com/857004/85301006-945ecb80-b4a7-11ea-8ee7-48ff560c684d.png)

... when checking (i.e. just loading) this document: https://languagetool.org/files/languagetool-test.odt

**Comment by FredKruse** [comment]
@danielnaber: The rule crashes because speller isn't initialized by the extension. I assume, you activated Ngram in the option panel. Unfortunately, I'm not familiar with the rules called by Ngram. So, I wonder if the UpperCaseNgram rule should be called by the extension. If it should be called, then the null pointer exception has to be fixed at the MorfologikSpellerRule, else I have to deactivate the rule by the extension.

**Comment by danielnaber** [comment]
> So, I wonder if the UpperCaseNgram rule should be called by the extension.

Yes, but I it uses a speller, and if there's never any speller in the LO context, it has to be turned off? I just tried adding `if (spellerRule == null) {` ad the top of the `match()` method, but it still crashes, not sure why.

**Comment by FredKruse** [comment]
Bug is fixed, I close the issue
