### ISSUE TITLE
[fr] mistake with "du"

### ISSUE THREAD

**Issue by thelittlefireman** [languagetool-org/languagetool#3280]
In these sentences 

```
Je fais du l'architecture. J'ai du pains.
```
The first `du`, should be suggested by `de`. In my knowledge, there is no word with `de l'` in French.

In the second sentence, `du` should be followed by a singular word (no plurals).

Try it in https://bonpatron.com/ if you want more information.

**Comment by jaumeortola** [comment]
Thank you. There is a rule for "du *pains>pain" in the Premium version of LanguageTool, but I am going to put it in the open-source version because it is a simple and obvious error.

**Comment by vkyfox** [comment]
The two prepositions "du" and "le" indeed cannot be one after the other. However, we have to pay attention to the very common misspelling of "dû" to "du" in which case the correction has to be on "du" instead of "le".
For example: "j'ai dû le manger" could become "j'ai du le manger" with a small typo.
