### ISSUE TITLE
[fr] undetected mistake (according to a user): beaucoup de photos

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#3452]
Beaucoup de photos et de vidéos sont utilisées.
should be
Beaucoup des photos et des vidéos sont utilisées.

**Comment by jaumeortola** [comment]
I think it is the other way around: `Beaucoup des photos -> Beaucoup de photos` (We don't have this rule, and perhaps we should)
Exception: `Beaucoup des photos que j'ai vues sont...`. 
@udomai @vkyfox

**Comment by baarsrj** [comment]
I don't know a lot of French. Just enough to understand a bit of what was written. It is just what a user entered in a form of mine as a suggested improvement.

**Comment by udomai** [comment]
> I think it is the other way around: `Beaucoup des photos -> Beaucoup de photos`

You're exactly right. Sometimes users are sure about wrong grammar ;)

In my opinion, writing a rule on erroneous "des" or "de" in "beaucoup de(s)" would be tough. A correct usage of "beaucoup des" is not always followed by an explicit relative clause:

_Beaucoup des réfugiés revenus en masse ont découvert que leur maison avait de nouveaux occupants._

Furthermore, a relative clause may still have a correct usage of "beaucoup de" to its left:

_Il y a vraiment beaucoup de gens qui lisent pour avoir le loisir de ne pas penser._

@vkyfox can you think of any context where "beaucoup de" or "beaucoup des" is definitely wrong, so that one could make a rule out of it?

**Comment by jaumeortola** [comment]
I would try the rule `Beaucoup des photos -> Beaucoup de photos` (only this direction, not the other one), with exceptions if there is and adjective (réfugiés revenus) or a relative clause (réfugiés que...). That's the best chance we have. We can try and see what happens with corpus.

**Comment by udomai** [comment]
I am pretty skeptical about this, I must say. The "des" carries a definiteness marker (i.e., the following noun is something that has previously been mentioned). This definiteness is frequently rooted in previous sentences. Any attempt at converting this to a rule is vowed to produce false positives most of the time. The use of definite articles across sentences actually is one of the most frequent instruments of text cohesion. Take this example:

_On en trouvera quelques exemples dans cette section. Il est vrai que beaucoup des témoignages ont un caractère anecdotique,..._

This would trigger the rule (no adjective, past participle or relative pronoun in sight), but looking at the previous sentence you can tell that the author of this text really meant to use "des" ("Sure, many of **these** reports are anecdotal,...").
On SketchEngine, I have found 398 examples.

**Comment by jaumeortola** [comment]
> I am pretty skeptical about this, I must say.
You are right. There are other structures that make it even more difficult ("Ça dépend beaucoup des vendeurs.").

**Comment by jaumeortola** [comment]
The rule BEAUCOUP_DES, with the pattern "avoir + beaucoup de(s)", works as expected.
