### ISSUE TITLE
[es] "como estas" not found

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3503]
> Hola, mi amigo como estas?

![Bildschirmfoto 2020-08-31 um 12 53 02](https://user-images.githubusercontent.com/37363/91712894-f82d0100-eb88-11ea-90c8-1e514a748f42.png)

**Comment by udomai** [comment]
Four errors! Only one spotted.

**Comment by udomai** [comment]
"Como estas" is actually tough: "¿Quieres manzanas verdes, como estas?" or: "¿No puedo comer las manzanas que están en la cocina? ¿Entonces como estas?

**Comment by jaumeortola** [comment]
We have already many rules for "como estas/cómo estás". 
The next step to take is to create a rule differently: always detect "como estas" (with a few exceptions). 

Punctuation errors (like the missing comma after `amigo`) are tricky. But I will create a rule for `..., cómo estás?` because it is a frequent sentence.
