### ISSUE TITLE
[en] loop anymore / any more

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3514]
> I don't see the graphs any more at e.g. https://www.foobar.com.

anymore -> any more -> anymore -> ...

**Comment by udomai** [comment]
I've looked at [#759](https://github.com/languagetooler-gmbh/languagetool-premium/issues/759). @MikeUnwalla, do you confirm that we should always recommend writing "anymore" as two words in BrE?

In AmE, we must distinguish the adverb "anymore" from incidental co-occurrences of "any" and "more".

Currently, we have three rules:

- ANYMORE in en-GB\grammar.xml (_anymore > any more_, no exceptions)

- ANY_MORE in en-US\grammar.xml (_any more > anymore_)

- ANYMORE_ADVERB in en\grammar.xml (_anymore > any more_)

These last two can cause loops. I have eliminated loops for the most frequent contexts (according to SketchEngine) [here](https://github.com/languagetool-org/languagetool/commit/5bf192a69b76896fdfbc92f46308950d872b7711), but this is more of a bodge than a systemic solution.

Since the rule ANYMORE_ADVERB is superfluous in en\grammar.xml for a user with BrE settings, we could migrate it to en-US. That way en-US\grammar.xml would have two rules: one to correct _anymore_ where it should be written as two words, and one for _any more_ where it should be written together.

In any case, the two rules that pull any_more apart or sew it together need to be coordinated systematically, so that they cannot produce any loops **any longer** (<-- dodged a bullet there). That one will be a doozy. New issue?

**Comment by MikeUnwalla** [comment]
> do you confirm that we should always recommend writing "anymore" as two words in BrE.

Yes (personal preference). But, you have seen #795 that some authorities accept 'anymore'. So ideally, have a style rule (which is not as dogmatic as a spelling rule that says the spelling is wrong).

**Comment by SkyCharger001** [comment]
Just an idea: would it be possible to get LT to check if directly subsequent 'corrections' would cause a reversion?

**Comment by udomai** [comment]
The issue can be closed, I have fixed this kind of loop. We might have to untangle those three rules in the future. We must take into consideration that a BrE-specific rule must be integrated into ZA, NZ, AU etc. if it applies over there, too. We might want to check for any more looping potential between en\grammar.xml and variety-specific grammars.

I will address this in a separate issue in the future.
