### ISSUE TITLE
Part of speech analyzing issue -NNS misidentified as VBZ

### ISSUE THREAD

**Issue by jahuang-sh** [languagetool-org/languagetool#3515]
"There is one dogs."
 In this sentence, "dogs" is identified as VBZ. 
Seems so in this pattern 'one' + NNS.
This error thus cannot be matched.

Note: With number '1', the analysis is correct. e.g., "There is 1 dogs"

**Comment by heyuluo** [comment]
Is this problem fixed? Connecting the server "https://languagetool.org/api/v2/check", it seems like this problem is still here.

**Comment by MikeUnwalla** [comment]
@heyuluo, the disambiguation problem is fixed (https://github.com/languagetool-org/languagetool/commit/ec6db2d5f39f113658d23749144da54fc1a336d9).

But, LT does not find the error because there is no rule. There is an open issue for this problem (https://github.com/languagetool-org/languagetool/issues/3519).
