### ISSUE TITLE
Handling of huge LO-documents: Save internal Cache to file

### ISSUE THREAD

**Issue by FredKruse** [languagetool-org/languagetool#3624]
One way to shorten time of checking huge documents is to save the cache:

- Save the internal cache (document cache and result caches) to a file, when the document is closed. 
- Read the cache, if the document is loaded again.
- The cache file is placed beneath the original document (same name, extension: lcz)

A first test version will be installed in the 5.2 snapshoot (after 2020-09-27). It is optional so far. It can be activated by the option panel.
The checking of the document is very fast (just the time LO needs to call the interface sentence by sentence), but a file is saved that is nearly so big as the ODT-document itself. The LT-cache-file is compressed to GZIP-format.

**Comment by KnowZero** [comment]
Since I got another large document to check, I figure i'd try out the latest snapshot 2020-12-08. And the cache file option was enabled by default, but it didn't work. I am on Linux Mint 19.3, I tried with defauly LO 6 and the Flatpak LO 7 versions and it didn't work on either. Did something break?

Otherwise, to comment on a few things.

1. It might make more sense to not only have it as a checkbox but also have a minimum line count input. So one can say to only create a cache if it is over 1000 lines/sentences.

2. Will the cache deal with upgrades/rule changes/profile changes? 
- Keeping track of all that might be a bit difficult and a lot of work, but at bare minimum a notification saying the cache for this document is outdated/you used a different profile, would you like to reload the cache.
- in same sense if the document has been modified say remotely, will the cache know?

**Comment by FredKruse** [comment]
@KnowZero : The save to cache file should work. The place to save cache files has changed. It is a subdirectory 'cache' in the LT configuration directory. You should see a message in the LT log file, if the cache was saved.
 
Thank you for your ideas. 
The first one is already implemented in the current snapshot. The cache of documents with less than 30 paragraphs are not saved (in the version just committed, I changed it to 50 paragraphs). This option is activated by default. If the option will be deactivated, the saving mechanism is deactivated independent of the size of the document.

The second idea is implemented in the version just committed (next snapshot). It compares the version of LT inside the saved cache with the version currently running (Note: the timestamp is not added to snapshots, so all snapshots of one version are treated as the same version). It also compares the disabled and enabled rules and the disabled categories. The saved cache is rejected, if anything is not the same.

**Comment by KnowZero** [comment]
@FredKruse : Okay I did a test on december 12th snapshot with a 75k word file on a i7-4600U cpu and sata ssd

With word2vec and ngrams plus default rules. The normal version took about 5 minutes and the cache version took only around 30 seconds :)

For the first one, I meant letting the user decide the amount. I also think lines or words are a better than paragaphs, the reason is this. I have a notes file where everything is on its own line so it thinks that file has 50+ paragaphs despite it being less than 7k characters. Well the notes file doesn't really need grammar checking but just pointing out scenarios. Other scenarios I can guess that things might show up as paragraphs would be a play where each thing is its own line.

On that note, would it also make sense to add a button to clear cache? I could do that manually, but for the non-tech users they might be interested in clearing it for either security reasons or simply adding up of space.

Anyways, this already helps quite a lot with large documents, thanks :)

**Comment by FredKruse** [comment]
Implemented cache saving mechanism:

A mechanism has been implemented since LT 5.2, which saves the LT caches to a file before a document has been closed. If exists, the cache file will be read, before the first check of a loaded document will be done. The results of LT checking will be read from the cache instead of check the text again. So, the process of marking the matches inside the text speeds up by a factor of nearly 10.

The following conditions have been implemented:
- All LT caches will always be saved if the number of characters of the document exceeds 25,000.
- If a cache file exists, it will be read before a document will be checked.
- The cache file will be ignored, if the version has changed or the disabled/enabled rules in the configuration file have changed (HINT: The date of version will not be proofed. So all snapshots of one version will be treated as the same).
- The saving of cache files can be (optionally) switched off by the option panel.
- The cache file will be stored in the directory 'LT configuration directory'/LibreOffice/cache. The size of a cache file is of the same magnitude as the document (HINT: The cache files will already been stored in a zipped format).
- A cleanup mechanism has been implemented. Cache files will be deleted, if the document path doesn’t exist anymore or if the cache file is older than a year. If the number of characters of a document falls under 25,000, the cache file (if exists) will also be removed.

**Comment by KnowZero** [comment]
Nice! I'll give it a shot in every day use and will comment if I notice anything :)

Also, another thing I just thought of. The saving is on close right? Let us say you are editing a file and save it. Then your pc crashes or libreoffice crashes. Your cache is pretty much lost since the document was changed but the cache was not updated.

Does it make sense to also make another cache on save, not just close? 

And a seperate cache for autosave? So if the user chooses to restore autosave, it will load the autosave cache?

**Comment by FredKruse** [comment]
These are interesting ideas, but I think they are a bit oversized. On one hand the cache will be totally new created, if anything changes (version of LT, new configuration). On the other hand no information of the user is lost, if the PC or LO crash. LT will start the check at the last status of cache. The PC has to work a little more, as if the cache was saved. This is not critical, I think.
Can we close this issue?

**Comment by KnowZero** [comment]
@FredKruse - At least the option to save cache on save?

As for closing the issue, that is up to you since you are the OP. I am merely offering suggestions based on my experience. I can always open a new issue if I run into new problems or inconveniences.
