### ISSUE TITLE
Words with Hyphens are unknown words

### ISSUE THREAD

**Issue by lindt** [languagetool-org/languagetool#363]
Given the English Word "behaviour-driven development", LanguageTool will report "behaviour-driven" as an unknown word, but "behaviour" and "driven" are both valid words. Since 2.6 the spell checker at least accepts it.
My only solution currently is, to add "behaviour-driven" to the glossary file. But this is wrong.

What should be done, that "behavior-driven" is not reported falsly as unknown word?

Would be appreciated if anyone could give me feedback. I would also be fine with a Classname, that I should fix. Just want to make sure, that I'm using the tool as it is intended to be used and that I'm not missing something.

Changelog for Version 2.6 (2014-06-30):

> -English:
>     -The spelling rule now accepts words with hyphens if the parts are valid words.
>      For example, "web-based" is accepted now. This avoids a lot of false alarms.

**Comment by baarsrj** [comment]
For Dutch, this should stay this way, to prevent nonsense combinations.
Op 2 feb. 2016 8:05 PM schreef lindt <notifications@github.com>:Given the English Word "behaviour-driven development", LanguageTool will report "behaviour-driven" as an unknown word, but "behaviour" and "driven" are both valid words Since 26 the spell checker at least accepts it
My only solution currently is, to add "behaviour-driven" to the glossary file But this is wrong

What should be done, that "behavior-driven" is not reported falsly as unknown word?

Would be appreciated if anyone could give me feedback I would also be fine with a Classname, that I should fix Just want to make sure, that I'm using the tool as it is intended to be used and that I'm not missing something

Changelog for Version 26 (2014-06-30):


-English:
    -The spelling rule now accepts words with hyphens if the parts are valid words
     For example, "web-based" is accepted now This avoids a lot of false alarms

**Comment by danielnaber** [comment]
`behaviour-driven` is British English, so make sure you set the language to en-GB. en-US will accept `behavior-driven`.

**Comment by lindt** [comment]
> behaviour-driven is British English, so make sure you set the language to en-GB. en-US will accept behavior-driven.

sure that.
take _test-driven example_ or the example which nagged me today _delay-change threshold_

**Comment by danielnaber** [comment]
How exactly are you using LT? I cannot reproduce these issues on https://languagetool.org.

**Comment by lindt** [comment]
I'm using it the following way:
`sudo gem install gherkin_language --no-format-exec` (For Details: [gherkin_language](https://github.com/funkwerk/gherkin_language) )
then:
`echo "Feature: Test-driven development" > test.feature && gherkin_language test.feature`

Internally it's an `java -jar languagetool-commandline.jar --list-unknown --api --language en-US -`.

The _unknown words_ feature is activated because:
 - it allows to build up a domain specific glossary
 - to be sure, that the tagger works correct
 - it's working quite well except the hyphen issue

https://languagetool.org AFAIK has the _unknown words_ feature disabled. So it's not reproduceable there.

**Comment by milekpl** [comment]
You're doing it wrong… "Unknown words" are words that have not been assigned a part-of-speech tag, not the words that are misspelled.

**Comment by lindt** [comment]
but if you need the whole sentence to be tagged, what should you do?
Is it correct that the tagger ignores words?
It's probably not that serious for libre office documents, but I'm doing some analytics based on the tagged words.
Remove the hyphens just for the tagger could be a solution, but then I would need to analyze the sentence twice, which is at least cumbersome, maybe also wrong.

How should a phrase like _"test-driven development"_ be annotated?
