### ISSUE TITLE
[fr] user feedback

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3679]
Feedback from a French user:

> Correction : Mes anciennes expériences et la formation professionnelle que j'ai effectuées = effectuée 
> Explications : Si « professionnelle » est l’antécédent du relatif « que », vérifiez l’accord du participe « effectuées ».
>
> Il me semble que si cela est à ne pas accorder c'est car on utilise l'auxiliaire "avoir" et donc on n'accorde pas ???

Not sure what she means, @udomai @vkyfox @jaumeortola

**Comment by udomai** [comment]
The user means that, in general, the past participle is not adapted in number and gender to the object if the perfect tense is formed with "avoir". The user is wrong. When there is a personal pronoun or a "que", the past participle changes according to the object.

But: The user has stumbled upon a real weak spot in the rule. We need to make the rule recognize that, if an object consists in singular noun phrases connected by "et", those behave like a plural noun phrase.

`**[D] [A] [J] [N . s]** [et] **[D] [A] [J] [N . s]** [que] [SUJET] [V avoir] **[V ppa . p]** ...`

_**Le stage** et **la formation professionnelle** que j'ai **faits** ont été importants pour ma carrière._

Right now, the rule QUE_AVOIR[4] tells me I should make "faits" into "faite" because it only sees _formation professionnelle_.

**Comment by vkyfox** [comment]
And done! https://github.com/languagetool-org/languagetool/pull/3690
