### ISSUE TITLE
[pt] barbarisms-pt file needs review

### ISSUE THREAD

**Issue by neoscopio** [languagetool-org/languagetool#3685]
The file needs a serious review. It's mostly bad, irrelevant, plain wrong or misleading.
Probably best to deactivate until review.

One example for sample:

soirée=matiné

I don't think no one would write "soirée" by mistake or distraction, so the general rule would suffice. But the example suggests the **opposite** meaning for the French word ...

There are many, many, many more.

**Comment by danielnaber** [comment]
@marcoagpinto

**Comment by danielnaber** [comment]
@marcoagpinto

**Comment by neoscopio** [comment]
Well, maybe just a few more examples:

speaker=presidente de parlamento
speed=estimulação
spleen=tédio
sporting=desportivo
(...)
Gee... It hurts.

**Comment by marcoagpinto** [comment]
@danielnaber 

All his examples are wrong.

Do you agree, @jaumeortola ?

**Comment by marcoagpinto** [comment]
ops

It is the examples Tiago added.

**Comment by marcoagpinto** [comment]
@jaumeortola 

Is it possible for you to review/edit the file?

Almost all the words there were added by Tiago Santos when he was member of the team.

**Comment by neoscopio** [comment]
So, I've done a very quick review, I don't really know your criteria, so feel free to toss it. It was just a first pass, I just comment the lines. Some were just plain translations I don't think are relevant (just my opinion) so I comment them also, I've kept the ones I feel (I'm no expert by any means) that might be useful.
[barbarisms-pt.txt](https://github.com/languagetool-org/languagetool/files/5371300/barbarisms-pt.txt)

**Comment by marcoagpinto** [comment]
@neoscopio 

Thank you for the .txt file.

I will have a closer look at it tomorrow.

I need to get some rest as I have already dedicated several hours to LanguageTool today.

**Comment by udomai** [comment]
@marcoagpinto, thank you very much for your work and dedication, they are much appreciated!! :)

**Comment by marcoagpinto** [comment]
I have been working on it, but it will take a few more hours analysing line by line and fixing/adding words.

@neoscopio Some of your new words I am adding to the italic list, such as "app" and "apps" which are more common to say in English. Also, "bottom-up" is added to the italic list since it is a technical term: "abordagem bottom-up".

**Comment by marcoagpinto** [comment]
@neoscopio 

I am around half of the file ("mRNAs=ARNs mensageiros"):
https://github.com/languagetool-org/languagetool/commit/53277ee29bc55a5b601288af40052da987bcdc11

Tomorrow I will continue.

**Comment by marcoagpinto** [comment]
And: https://github.com/languagetool-org/languagetool/commit/0b3d79c87c9e00b3532a17d8f0c65e663bccbd75

**Comment by marcoagpinto** [comment]
@neoscopio 

Done!

https://github.com/languagetool-org/languagetool/commit/6a37e515d2a378aaf0eb456d415c2a097bdd4a56

I have gone through the whole list and improved/fixed as much as I could and also removed duplicates.

Words such as "upgrade" were removed and added to the grammar.xml list of foreign words since the translation it used wasn't accurate.

Can we now close the ticket?

**Comment by neoscopio** [comment]
Hi Marco, I'm glad the file was reviewed so fast and I'm sure is much better now, thanks.  I Didn't see it yet, but I'll reopen if I find the need.
