### ISSUE TITLE
[fr] Wrong description for rule AUX_ETRE_VCONJ

### ISSUE THREAD

**Issue by Wild94** [languagetool-org/languagetool#3766]
The second sentence of the description of the rule AUX_ETRE_VCONJ is wrong :
"Quant à l'accord, celui-ci s'accorde avec le COD s'il est placé avant l'auxiliaire ; sinon il restera au masculin singulier." is only true with the "avoir" auxiliary, not "être".
For "être", the rule is always that it should match the genre and singular/plural of the subject.
So the description should be "Quant à l'accord, celui-ci s'accorde en genre et en nombre avec le sujet du verbe."

Also the link to the rule on reverso is wrong, as it is the same as "avoir". It should be
https://grammaire.reverso.net/accord-du-participe-passe-conjugue-avec-etre/

**Comment by udomai** [comment]
Hi @Wild94, thank you for the input! Bien vu. J'ai changé le message tout de suite ! Si tu vois d'autres erreurs de ce genre, surtout n'hésite pas à nous le signaler. Merci encore et une excellente journée à toi :)

**Comment by Wild94** [comment]
Merci pour cette correction :) ! mais il manque un petit bout.

L'adresse de référence de la règle vers Reverso pointe vers la règle pour "avoir" et non pour "être" (line 13037 of grammar.xml).
La règle pour "être" devrait pointer vers cette page :
https://grammaire.reverso.net/accord-du-participe-passe-conjugue-avec-etre/

Also may I suggest altering the name of the rules? They both have the same verbose name.
line 13013 : "Auxiliaire être suivi d’un verbe conjugué"
line 13081 : "Auxiliaire avoir suivi d’un verbe conjugué"

J'aurais bien fait la PR moi-même, mais je ne maîtrise pas cette partie-là de Git ^^.

**Comment by udomai** [comment]
Thank you for the further pointers!! I totally didn't see the mismatched URL in there.

The rule RPERSSUJ_ETRE_V was obviously placed there by mistake, since subrules do not take IDs. It is an independent rule for a special case of "_être_ suivi de forme finie" (so it doesn't go into the other rulegroup).

Thank you for spotting both those things!

Quant au noms incombrants : Ta proposition me paraît très sensée en principe. Cependant, les noms des règles doivent au même temps être concis, mais aussi précis. Je vais discuter cela avec l'équipe, je crois qu'il y aura nombre de règles dont les noms ne sont pas optimaux. Si nous décidons que le jeu en vaut la chandelle, nous allons vérifier les noms des règles systématiquement :)

Dans le cas de "Auxiliaire être suivi d’un verbe conjugué", par exemple, que proposerais-tu ? La meilleure solution qui me viendrait à l'esprit, ce serait quelque chose come "Être suivi d'une forme finie". Aurais-tu une meilleure idée ?

**Comment by Wild94** [comment]
Sans aller jusqu'à changer complètement les noms, je suggérait simplement de différencier les deux règles qui ont le même nom.

Si j'ai bien compris ce qu'est une forme finie, ta proposition peut fonctionner. Elle a cependant le désavantage de ne pas forcément être compréhensible par tout le monde au premier abord (j'ai du regarder ce qu'était une forme finie pour la comprendre).
Les anciens noms ont l'avantage d'être très proche de ce qu'on entend en cours de langue et de bien identifier le rôle de être/avoir en tant qu'auxiliaire et non verbe dans ce contexte.

Pour mieux comprendre le fonctionnement de la règle, j'avais en tête ces deux exemples (qui me passent juste par la tête) :
- Elle est très regardée à la TV.
- Elle est très regardante sur les bonnes manières.

La règle fonctionne-t-elle dans les deux cas ? (a) ou uniquement dans le premier ? (b)

a/ Si elle fonctionne sur les deux cas, alors je pense que ta proposition est plus pertinente, "être" étant un auxiliaire dans la première et un verbe dans la seconde. Peut-être que la formulation "Être suivi d'un participe" est plus adaptée/compréhensible par tout le monde ? Dans ce cas il faudra sans doute également reformuler la description :
"Après l’auxiliaire « \1 », le verbe devrait être au participe passé" 
-> "Après « \1 », le verbe devrait être au participe passé ou présent"

b/ Si elle ne fonctionne que sur la première, alors elle ne concerne que "être" dans son rôle d'auxiliaire et l'ancien nom/ma suggestion me paraît plus approprié(e).

Concernant avoir, je crois que les règles ne le concernent que dans son rôle d'auxiliaire. Je ne suis pas sûr qu'il soit possible de reformuler le nom, mais uniquement de le préciser pour identifier immédiatement qu'il s'agit de l’auxiliaire "avoir".

**Comment by udomai** [comment]
Hi @Wild94, sorry for the long line...

As to your two examples:

> * Elle est très regardée à la TV.
> * Elle est très regardante sur les bonnes manières.

The second sentence is covered (in case the user were to write "regardant") by another rule.

The rule in question only concerns "être" as an auxiliary, so its name should be okay.

The rules' names and IDs serve different purposes. The everyday user never sees the ID and only comes in contact with the name when they [browse through the rules here](https://community.languagetool.org/rule/list?offset=0&max=10&lang=fr&filter=auxiliaire+suivi&categoryFilter=&_action_list=Filtrer). In that case, it actually makes sense that the two rules for _avoir_ and _être_ have the same name: That way the user sees that we have (a) rule(s) that covers an auxiliary followed by a homophonous finite verb form instead of the past participle. The examples then tell them that both French auxiliaries are covered.

Anyone delving deeper into the inner workings of LanguageTool has the unique ID to identify any rule unequivocally.

This is why I would leave it as is for now. But we will have a look at the rule names and make sure they are used following the same logic all the time!

Ta contribution nous a grandement aidé à améliorer ces règles. Si tu vois d'autres problèmes, n'hésites pas à nous les signaler. Tes contributions sont toujours appréciees ! :)

**Comment by Wild94** [comment]
Thank you @udomai for taking the time to discuss here! (and for making the PR for me, I swear I will learn to make them.)

Je continuerai à garder l’œil ouvert quand j'utilise le logiciel ;)
