### ISSUE TITLE
[ca] user feedback "dona"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3832]
> Em corregeix el "dona" a "dóna" quan ja no és un accent diacrític.

@jaumeortola not sure what the user means :)

**Comment by jaumeortola** [comment]
It is a change in the norm. Same issue: https://github.com/languagetool-org/languagetool/issues/3671

The only solution that can make everybody happy at this point is a user option like the first one here (from Softcatalà). 
One value enables a whole category and disables a rule. The other value the other way around. 

![imatge](https://user-images.githubusercontent.com/4289501/98707349-3d875f00-2380-11eb-855a-fe658f508a3e.png)

**Comment by jaumeortola** [comment]
@tiff There is a special feature for "smart quotes" rules (and other rules) in English, isn't it? They can be enabled and disabled, at least on the browser add-on. Could something similar be done for these Catalan rules? But it is not simple because it needs to disable a category and enable a rule. 

We need a more general solution for user options and for all languages.

**Comment by jaumeortola** [comment]
Closing because the same issue is here: #3671

**Comment by tiff** [comment]
@jaumeortola sorry for my late response. We don't have a mechanism like this in the browser add-on. We can only disable rules by default.
