### ISSUE TITLE
[fr] user feedback "ceci" / "cela"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3860]
> J'ai écrit « Cela est un test : il faut faire ceci. » et aucune faute n'a été signalé. Or, il aurait fallu écrire « Ceci » à la place de « Cela ».

**Comment by udomai** [comment]
I am very skeptical about this artificial error...

The logic is the same in English: _ceci_ (just like _this_) is used for things that are close (in time and space) to the speaker, _cela_ (same as _that_) is used for things that are somehow "further" away from the speaker.

_Cela est un test._ Is a grammatically correct sentence, corresponding to "That's a test.". If you're saying that those same words are the test, "ceci" (and "this") would be in order. But if you are referring to something that has been mentioned before (i.e. which is one sentence "further" away), you do say "Cela est un test." just like you'd say "That's a test.".

This sentence is grammatically correct (and just means something different from what the user intended) and this is not a mistake a native speaker would make randomly (this is a constructed error).

That's why I'd say we can go ahead and close the issue.
