### ISSUE TITLE
[ca] error not shown in webpage

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#3934]
The match on this sentence (the missing period at the end) is not shown on the webpage, but it is shown by the API and by the browser add-on. 

https://languagetool.org/api/v2/check?language=ca-ES&text=Aquesta%20%C3%A9s%20una%20frase%20llarga%20que%20no%20t%C3%A9%20punt%20al%20final%20i%20per%20tant%20%C3%A9s%20segur%20que%20hi%20ha%20un%20error

**Comment by jaumeortola** [comment]
It's very strange. I cannot understand what happens. There is a rule in Spanish that is exactly the same, and it works.

**Comment by danielnaber** [comment]
There are a few special cases where the add-on and website filter out rules to avoid false alarms. @tiff knows whether this is such a case.

**Comment by tiff** [comment]
@jaumeortola the new check-as-you-type input field ignores rules that suggest punctuation at the end of a sentence. These rules are synthetically marked as "picky" (and are therefore only visible when the "picky mode" is active). 
We had to do that because users would get annoyed when the last word would always be highlighted. I'm open to suggestions on how to improve this

**Comment by jaumeortola** [comment]
I understand. These rules only match when sentences have more than 20 words. I didn't find them annoying, but probably they are.

**Comment by tiff** [comment]
I think they are only annoying when the check is happening in real time. The add-on knows where the user's cursor is, so eventually we can activate them for sentences that are far away from the user's current selection
