### ISSUE TITLE
[ar] user feedback

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4002]
> لكم الشكر 
> البرنامج لا يميز بين همزتي الوصل والقطع كيف يمكن تطوير او تثبيت ذلك
> كما انه عند كتابة كلمة تبدأ بهمزة بعد كلمة اخرى يعتبر الكتابة خطأ لماذا مثلا 
> تطوير او
> يعتبرها كتابة خطأ 
> وكانها كلمة واحدة 
> مثال ثان
> كلمة 
> اخرى 
> لا يقدم لها بدائلك بهمزة قطع 
> مع الشكر

**Comment by danielnaber** [comment]
@sohaibafifi

**Comment by sohaibafifi** [comment]
Thank you, 

This rule is not implemented yet, [for more information](https://en.wikipedia.org/wiki/Hamza#Hamzat_al-waṣl), and [Sun and moon letters](https://en.wikipedia.org/wiki/Sun_and_moon_letters)

@linuxscout Can you please add this to the roadmap? I think this can be easily handled using Java rules

**Comment by linuxscout** [comment]
Salam, 
Thank you for your notes,
For spell errors like او or اخرى, LanguageTool use Hunspell with arabic dictionary, It generate a lot of suggestions, but it show few ones.

We will work on it.

**Comment by KathKal** [comment]
@sohaibafifi 
>  البرنامج لا يميز بين همزتي الوصل والقطع كيف يمكن تطوير او تثبيت ذلك

LT _does_ differentiate between Hamza Wasl and Hamza Qati. Try:
انت تعرف ذلك، فإنتبه. قلت: فانتبه.

انت - تصحيح: أنت

LT did not accept Hamza Wasl (ا) in (انت) and suggested the right Hamza Qati (أ) in (أنت).


فإنتبه - تصحيح: فانتبه; فأنتبه; فإتبه; فنتبه; فإتبهن; فمنتبه; فننتبه; فتنتبه; فلنتبه; فينتبه; فسنتبه

LT did not accept the Hamza Qati (إ) in (فإنتبه) and suggested the right Hamza Wasl (فانتبه), Hamza Qati in possible right words (فأنتبه, فإتبه, فإتبهن), or words without Hamza. All these are right suggestions.

فانتبه - صحيحة

LT accepted the right Hamza Wasl (ا) in (فانتبه).

> كما انه عند كتابة كلمة تبدأ بهمزة بعد كلمة اخرى يعتبر الكتابة خطأ لماذا مثلا
تطوير او
يعتبرها كتابة خطأ
وكانها كلمة واحدة

This is not always the case. But for your example, it is because you misspelled (او).

The word you wrote (او) is an error, as there is only possibility to spell it: (أو). In this case, the suggestion (تطويرا و) is the only left possibility!

A following rule rightly marked (او) as a wrong spelling and mentioned its correct form (أو). Doing this correction leaves the phrase without error.
Rule developer @linuxscout may consider giving the priority to Hamza correction (او > أو) rule, and maybe hiding the other rule if this one is applied (if they occur in one segment).

You can try this example to see that it is not always the case:

اردنا تقديم إلتماس.

LT rightly suggests (التماس) instead of (إلتماس); it does NOT simply connect a word to another if the following one has (Hamza)!

> كلمة
اخرى
لا يقدم لها بدائلك بهمزة قطع

It is only the online-version that gives limited suggestions (5) that lacks the word (أخرى); perhaps the developer @danielnaber wants to preserve server resources:

![LTWeb_LimitedSuggestions](https://user-images.githubusercontent.com/100029647/155132188-206c508b-b5da-4d22-87de-f74433579233.png)

The desktop version, for example, has the word (with other 14 suggestions):

![LTDesktopSuggestions](https://user-images.githubusercontent.com/100029647/155132253-c38f2fd2-ad1b-4bd4-8f2b-d9654a74b86c.png)

**Comment by linuxscout** [comment]
Thanks for all your feedback, 
I think that are some error on handling spaces between words where the second is mistaken.

**Comment by linuxscout** [comment]
@danielnaber please close this issue.
