### ISSUE TITLE
Cyclic correction of full time / fulltime

### ISSUE THREAD

**Issue by Moohan** [languagetool-org/languagetool#415]
When checking in British English the text;
> I was also working full time.

It suggests 'full time' should be one word 'fulltime' however if

> I was also working fulltime.

is checked it says 'fulltime' is a spelling error and should be 'full time' or 'full-time'

**Comment by MikeUnwalla** [comment]
The cyclic correction occurs for all language variants.

The suggestion 'fulltime' is not correct for BrE. Adjective and adverb use a hyphen. The noun is 2 separate words. For example, refer to www.oxforddictionaries.com/definition/english/full-time?q=fulltime.

My copy of Merriam Webster's (American) dictionary gives the same information for AmE. (Use 'full-time' or 'full time'.) COCA gives these frequencies:
fulltime: 317
full-time: 9454
full time: 2103

The incorrect analysis is caused by this line in en/compounds.txt: full-time+
Refer also to https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/CompoundRule.java

I removed full-time+ from compounds.txt. The change affects all the language variants. But, the Morfologik speller rules find the tern 'fulltime' for all language variants except AmE.
