### ISSUE TITLE
[fr] Bad suggestion for verb prévoir

### ISSUE THREAD

**Issue by bperel** [languagetool-org/languagetool#4328]
> Il >prévu< d’équiper en 2023 leurs pilotes d’un viseur de casque et de les doter d’un nouveau système de communication par satellite

LanguageTool suggests: 
prévirent
prévis
prévisse
prévissent
prévisses

whereas "prévit" should be suggested. not sure if similar verbs have the same behavior.

**Comment by jaumeortola** [comment]
Thank you. This problem is general in the rule group ACCORD_R_PERS_VERBE. The rules are not prepared to generate a personal form (e.g. 3rd person singular) from a non-personal form (infinitive, participle...). 

We will need to duplicate the rules to generate the correct suggestions. Number and person come from the pronoun. But the tense (present, past...) should be guessed or invented: il prevoit, il prévit, il a prévu...

**Comment by bperel** [comment]
Thanks for your answer. In the case that I wrote though, it doesn't look like the gender was implied either, otherwise it would have suggested "prévoit" which is the present form. Or do I misunderstand what you say?

**Comment by udomai** [comment]
The FindSuggestionsFilter would make the right suggestions with `V.*3 s`, right? This would require a rule for each person-number combination.

**Comment by jaumeortola** [comment]
Gender (masculine/singular) is not used in this rule. It is person (1, 2, 3) and number (singular/plural). For example, in `il veux`, it converts `veux` (pres ind 1/2 sing) into `veut` (pres ind 3 sing). The verbal tense (indicatif présent) is kept. 

In `il vu` it tries to generate "participe passé 3 sing", which doesn't make sense. In fact, all the conjugation is generated, but only five forms are shown. 

> The FindSuggestionsFilter would make the right suggestions with `V.*3 s`, right? This would require a rule for each person-number combination.
Yes. That's a way to do it.

**Comment by jaumeortola** [comment]
Fixed with new rules PRONSUJ_NONVERBE.
