### ISSUE TITLE
[en] false alarms PRONOUN_NOUN

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4495]
https://internal1.languagetool.org/regression-tests/via-http/2021-03-02/en-US/result_grammar_PRONOUN_NOUN[1].html

**Comment by jaumeortola** [comment]
Some common abbreviations like `rec'd` should be added as exceptions to the tokenizer and tagged properly.
Optionally, a rule can be created that suggests the full word...
For other less common words (maintain'd, fax'd...), there is no easy fix because `'d` is intrinsically ambiguous. It can be: -ed, had, would.

**Comment by udomai** [comment]
See also "OK'd": https://internal1.languagetool.org/regression-tests/via-http/2021-03-02/en-US/result_grammar_BY_PASSIVE_PARTICIPLE_BE[1].html

**Comment by jaumeortola** [comment]
A more general solution for rec'd and OK'd: https://github.com/languagetool-org/languagetool/commit/6f6221c32aae6fc294b54225e269d784c0571e90

**Comment by udomai** [comment]
There's also OD'd:

https://internal1.languagetool.org/regression-tests/via-http/2021-03-02/en-US/result_grammar_PRONOUN_NOUN[1].html
