### ISSUE TITLE
[pt] "eu ja"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4653]
"eu ja" is often added to the dictionary of Portuguese users. Is it a grammar mistake? Can we provide a better suggestion?

Google suggests: "eu já"

This is what we suggest:
<img width="410" alt="Bildschirmfoto 2021-03-22 um 14 22 43" src="https://user-images.githubusercontent.com/37363/111996243-199c0d00-8b1a-11eb-8450-2cf6b77acd6b.png">

**Comment by tiff** [comment]
Same for "é so"

**Comment by udomai** [comment]
and for "eu so"…

HUNSPELL shouldn't re-arrange the letters of two words, at least in the case of "so" and "ja", but suggest "já" and "só" (and leave "eu" and "é" alone).

@jaumeortola, can we immunize "eu ja", "eu so", "é ja", "é so" etc. in the disambiguator so that only "ja" and "so" are matched?

**Comment by marcoagpinto** [comment]
Sorry... I just got back from my job.

"eu já" is a kind of interjection?

"Alguma vez fizeste isso?"
"Eu já"

**Comment by marcoagpinto** [comment]
"eu só" also a kind of interjection?

"Quantos de vocês fizeram isso?"
"eu só"
