### ISSUE TITLE
Word Split breaks in docs with weird margians

### ISSUE THREAD

**Issue by Rdna123** [languagetool-org/languagetool#4661]
Split 'cat' and 'in' using language tools to show: [Google Doc with Error](https://docs.google.com/document/d/1mn8i0a_twOA5dJVsa1NVtznkvbflwlx3oqr7GL1Upnk/edit?usp=sharing)

e.i. turns "The catin the hat" to "Thecat in the hat"

**Comment by danielnaber** [comment]
Thanks for the report. I cannot reproduce that, could you send screenshots or a screencast? Which browser do you use?

**Comment by tiff** [comment]
I can reproduce it.

**Comment by tiff** [comment]
It happens when the browser is zoomed in. @Rdna123 can you confirm?

**Comment by Rdna123** [comment]
My browser is at 100% view both browser and google doc.

**Comment by tiff** [comment]
@Rdna123 which browser are you using?

**Comment by Rdna123** [comment]
I am using Google Chrome

**Comment by tiff** [comment]
Yesterday we have released a new version of our Chrome extension with a few fixes concerning Google Docs.
Could you re-check? For this, you would need to uninstall and re-install the extension here (otherwise it will take days to weeks until the new version reaches your computer):
https://chrome.google.com/webstore/detail/grammar-and-spell-checker/oldceeleldhonbafppcapldpdifcinji

**Comment by Rdna123** [comment]
@tiff I am unable to check till the end of spring break

**Comment by danielnaber** [comment]
Closing, as there was no reply
