### ISSUE TITLE
[fr] "visio"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4665]
One of the most ignored words is "visio". 
Does it make sense to add it to the dictionary? If so, do we need POS and/or a style rule suggesting the formal form?

https://fr.wiktionary.org/wiki/visio

**Comment by udomai** [comment]
Might be due to "visioconférence" being written "visio conférence", or the latter being abbreviated to "visio".

@Rebecca-auque, this seems like low-hanging, and quite relevant fruit :)

Could you whip up an Open Source rule that finds "visio conférence" and suggests "visioconférence"?
Could you write a Premium rule that suggests "visioconférence" when the user writes "visio" (unless followed by "conf[eé]rences?")?

I will add "visio" to the dictionary.

**Comment by tiff** [comment]
Just as a side note: For simple compounds that don't need much explanation consider adding them to the French compounds.txt (at the top of the file is a short explanation how to do it)

**Comment by udomai** [comment]
Oh yeah, that's true! Thanks for the tip, @tiff :)

Added the word here: 804c563943f20cc0376c3ad906491d153747034c

Added the compound here: 8fa75598f27caff6368730ee57ae781ba6aa99e9

**Comment by Rebecca-auque** [comment]
I wrote the rule for visioconférence in LanguageTool Premium.

**Comment by tiff** [comment]
I'm closing this
