### ISSUE TITLE
LibreOffice: "Check Text", "Recheck Document" weird behaviour

### ISSUE THREAD

**Issue by Elaborendum** [languagetool-org/languagetool#4698]
When clicking "Check Text", this is the dialog that pops up:

![image](https://user-images.githubusercontent.com/71190696/112744007-def30400-8f61-11eb-8b14-dbebc65a8090.png)

The only option then is to just close it.

And when clicking "Recheck Document", this dialog pops up:

![image](https://user-images.githubusercontent.com/71190696/112744048-27aabd00-8f62-11eb-9843-6edd51ad4073.png)

However, if I close that last dialog before doing anything and click on "Check Text" this very same last dialog will be the one to appear, leading to my confusion. What's exactly the difference between these two options? I don't use the extensions in other programs to compare.

Is this intended or is the second dialog supposed to appear when you click "Check Text"

Tested with 5.3-snapshot, similar behaviour in previous versions.

**Comment by FredKruse** [comment]
"Check Text" starts the check at the position of the cursor. I think the cursor was positioned at the end of the text as you start the dialog at the first snapshot.
The differences of "Recheck Document" are the following:
1. The check starts at the beginning of the document.
2. All "Ignore Once" entries are deleted (all matches are shown, even if you ignored them before).
3. A new check in the Background is initiated. All caches are deleted and new created (I am planning to separate this point to another function in version 5.4, because this function generates a high CPU-load for big documents. The cache should only be renewed if really needed).
So I think, both functions do, what they should. The functionality is similar to that of the spell checking dialogs of LO.

**Comment by Elaborendum** [comment]
Thank you, I somehow never realized that "Recheck Document" moved the cursor to the top.
