### ISSUE TITLE
[pt-br] false positive

### ISSUE THREAD

**Issue by albcunha** [languagetool-org/languagetool#4869]
Spellchecker flags this word as wrong: tão somente

It suggests: tão-somente

It was an misunderstood. The Brazilian Accademy of Letters, when first lauched it´s dictionnary, wrote it as "tão-somente", but later on they reviewed back to "tão somente".

Sources:
https://www.migalhas.com.br/coluna/gramatigalhas/128828/tao-somente--tao-somente-ou-taossomente
https://www.academia.org.br/nossa-lingua/busca-no-vocabulario
https://eduardosabbag.jusbrasil.com.br/artigos/121934013/as-encruzilhadas-do-acordo-ortografico
https://blogs.correiobraziliense.com.br/dad/hifen-tao-so-e-tao-somente/

**Comment by marcoagpinto** [comment]
@tiff @udomai @jaumeortola 

The word is in the pt-BR dictionary at line:
284707
pt_BR.dic

I don't want to edit .dic files.

**Comment by albcunha** [comment]
I don´t understand. Can i open up pt_BR.dic, change it and do a merge request?

**Comment by marcoagpinto** [comment]
I am not certain if it is that easy.

When I update the British dictionary, Yakov uses a script to convert the file.

So, I don't know if it is just a matter of deleting the word and then decrease the counter in the first line of the .dic.

**Comment by marcoagpinto** [comment]
Can someone tell me if that is all one need do?

**Comment by udomai** [comment]
Hi @marcoagpinto, the non-hyphenated version is corrected because `tão-somente*` and `Tão-somente*` are in `post-reform-compounds.txt`. You can just comment out those entries, or you use `+` or `$` to suggest the non-hyphenated version.

(You could also write a quick XML rule with a more helpful message, especially if there are more words like this. "De acordo com a reforma ortográfica, esta palavra escreve-se sem hífen.")

**Comment by marcoagpinto** [comment]
I commented it out!

Thanks!

https://github.com/languagetool-org/languagetool/commit/d5e744871808632b9b966493f7d896dcaa95d135
