### ISSUE TITLE
[pt] false alarm number at SENT_START

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4996]
Problema com as siglas art, arts. O número não deveria ser considerado como início de frase nesta sentença.

![image](https://user-images.githubusercontent.com/37363/117797869-ce1bfa80-b250-11eb-9cc6-de69e462369d.png)

![image](https://user-images.githubusercontent.com/37363/117797900-d6743580-b250-11eb-9b0f-f1b9734c80da.png)

**Comment by marcoagpinto** [comment]
@tiff 

Ahhhh.... it is very easy to fix.

I will fix it in the afternoon.

🙂

**Comment by tiff** [comment]
@udomai I think that segment rules are case-sensitive, that's why it splits at "Art." (even though "art" is already in the segment rules)

![Bildschirmfoto 2021-05-11 um 14 34 19](https://user-images.githubusercontent.com/37363/117815722-0bd74e00-b266-11eb-93da-59948598ddf3.png)

**Comment by udomai** [comment]
Okay, I've added the uppercase version as well – tomorrow, this should work as expected.

@marcoagpinto, I think "art" and "arts" can be removed from `added.txt` again. Otherwise, we won't be able to spot the typos "art" (instead of "arte") and "arts" (instead of "artes") anymore. If I'm not mistaken, "art." and "arts." are only correct if followed by a period, right?

**Comment by marcoagpinto** [comment]
> If I'm not mistaken, "art." and "arts." are only correct if followed by a period, right?

Right

**Comment by marcoagpinto** [comment]
https://github.com/languagetool-org/languagetool/commit/530a142e3dd45cfd767600d305895e9b4f8c2fec

https://github.com/languagetool-org/languagetool/commit/f5c38cca8c92feb3ab52eeee63488416ffeeac99
