### ISSUE TITLE
[en] walkaround and workaround

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#502]
I am personally often confused with this two word, as soon as "workaround" is to find a way to "walk" around the real problem, without actually solving it.  Probably LT should warn about possible word misuse...

**Comment by MikeUnwalla** [comment]
I think that walkaround/workaround is a candidate for a personal rule that you create in an external file (http://wiki.languagetool.org/tips-and-tricks#toc10).

Although LT has a category 'Commonly Confused Words', the rules are for words in context, and thus, each instance of a word does not give a warning. I cannot think how to add disambiguation to prevent an error message for each instance of the words.

English has many pairs of words that people confuse. In each pair of examples that follow, both of the sentences are correct:

This is stationary.
This is stationery.

This dessert is very hot.
This desert is very hot.

I will borrow the money.
I will lend the money.

I would appreciate guidance from the more experienced members of the team. Do you think that walkaround/workaround would be useful in LT?

**Comment by kostyfisik** [comment]
It is always possible to do a simple frequency analysis, e.g. using google search language:
"walkaround" -"walk around"
676k pages
"workaround" -"work around"
12 800k pages
two orders of magnitude - should warn!

stationary - 90.9 mln pages
stationery - 231 mln pages
same order, should not warn

dessert hot - 87.8 mln pages
desert hot - 13.4 mln pages
same order, should not warn (wow, dessert is hotter!)

"borrow the money" 2.58 mln pages
"lend the money" 336 k pages
probably could warn

"land the money" and "lend the money" are hard to test with google (as soon as you need money to bye or lend the land, and if you own some land you should probably have some money) so I used tatoeba sentence base:

cat tatoeba-sentences-eng.csv |grep lend|grep money|wc -l
134
cat tatoeba-sentences-eng.csv |grep land|grep money|wc -l
7
Probably should warn. If you restrict to "land" and "money" without comma of inflected "buy" in between this will give you no regressions in tatoeba. 

"bye" or "bay"  + "the" or "a"  should be replaced with "buy" +"the" or "a"

**Comment by yakovru** [comment]
Can be used n-gram for frequency analysis?
http://wiki.languagetool.org/finding-errors-using-n-gram-data

**Comment by kostyfisik** [comment]
It looks like the cases above are quite deterministic... So no need for n-gram concept, which is too hard for me to understand.

**Comment by MikeUnwalla** [comment]
@kostyfisik ,

@danielnaber added borrow/lend and land/lend to our confusion list (http://forum.languagetool.org/t/run-confusionruleevaluator-from-the-command-line/1087). To make LT find errors with those words, you you don't need to know about n-grams. You only download the n-gram data and tell LT to use it (http://wiki.languagetool.org/finding-errors-using-n-gram-data).

LT finds 'walkaround' as a spelling mistake.

COCA (http://corpus.byu.edu/coca/) gives these results for the 2-word terms:

work around (work=noun or verb): 744
work around (work=verb): 539
work around (work=noun): 205

walk around (walk=noun or verb): 2501
walk around (walk=verb): 2164
walk around (walk=noun): 337

NOW (http://corpus.byu.edu/now/) gives these results for the 2-word terms:

work around (work=noun or verb): 5209
work around (work=verb): 3371
work around (work=noun): 1838

walk around (walk=noun or verb): 10720
walk around (walk=verb): 8771
walk around (walk=noun): 1949

I think that a rule will not be useful for most users, because it will trigger too many false warnings. Thus, I am closing this issue.
