### ISSUE TITLE
[en] postag_replace for pronoun pair myself/I is not correct

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#5178]
The suggestion 'i' is not correct. The letter 'i' is not `PRP_S1S`.

```
<rule id="POSTAG_REPLACE_I" name="Postag replace with 'i'">
    <pattern>
        <token>Malcolm</token>
        <token>and</token>
        <marker>
            <token postag_regexp="yes" postag="PRP_R.*"/>
        </marker>
        <token chunk_re=".-VP" postag="MD"/>
    </pattern>
    <message>The reflexive pronoun '\3' should probably be the subject pronoun <suggestion><match no="3" postag_regexp="yes" postag="PRP_R(.*)" postag_replace="PRP_S$1"/></suggestion>.</message>
    <example correction="she">Malcolm and <marker>herself</marker> can write the letter.</example>
    <example correction="i">Malcolm and <marker>myself</marker> will help you.</example>
    <example>Jane and <marker>she</marker> can write the letter</example>
  </rule>
```

**Comment by jaumeortola** [comment]
The problem is in this line of the English synthesizer: https://github.com/languagetool-org/languagetool/blob/ee382bada673c7401a1727fb3b8917834fa542ef/languagetool-language-modules/en/src/main/java/org/languagetool/synthesis/en/EnglishSynthesizer.java#L130

In fact, we are converting to lowercase any capitalized word generated by the synthesizer. I don't know why. I can remove this conversion, and we'll see if there is any relevant change in the nightly differences.

**Comment by MikeUnwalla** [comment]
@jaumeortola , thank you.
