### ISSUE TITLE
[en] allow to

### ISSUE THREAD

**Issue by gilch** [languagetool-org/languagetool#533]
LanguageTool doesn't seem to detect this issue: https://english.stackexchange.com/questions/85069/is-the-construction-it-allows-to-proper-english

Here's an attempted rule produced from the LanguageTool Rule Editor.

``` xml
<!-- English rule, 2016-09-03 -->
<rule id="ALLOWS_TO" name="allows to">
 <pattern>
  <token regexp='yes'>allows?</token>
  <token>to</token>
 </pattern>
 <message>Allows [what/who] to?</message>
 <url>https://english.stackexchange.com/questions/85069/is-the-construction-it-allows-to-proper-english</url>
 <short>allows ? to</short>
 <example correction=''>It <marker>allow to</marker> compete at some international pageants to represent the island as a territory. This allows to quickly edit the last command in the case of a mistake.</example>
 <example>It allows them to compete at some international pageants to represent the island as a territory.</example>
 <example correction=''>This allows to quickly edit the last command in the case of a mistake.</example>
 <example>This allows the user to quickly edit the last command in the case of a mistake.</example>
</rule>
```

**Comment by MikeUnwalla** [comment]
I found many counter-examples that use 'allow/s to' correctly:

Incorrect: Unfortunately, this does not easily or quickly allow to edit the last command in the case of a mistake.
Incorrect: Pour the broth into a bowl and allow to cool. [Elision of 'the broth'/'it'. This construction is very common in instructions, specially recipes.]
Correct: This remains as a grave reminder of what we must not allow to happen again.
Correct: ... that is something that they wouldn't usually allow to happen.
Correct: ... in Medicare spending that the Democrats in Congress will never allow to take place.
Correct: ... the need for players to take greater care over what they allow to enter their systems, but it is not cheating.
Correct: They will exercise greater care in the future as to whom they allow to operate their vehicles, visit their apartments, ...
Correct: ... but it's not something that you will allow to crush you.
Correct: How much of my land do I allow to go fallow? Do I grow a different kind of crop?
Correct: The suffering from the past is a shadow that we allow to haunt us.

Also, past tense and passive voice:
Incorrect: This allowed to compete at some international pageants to represent the island as a territory. 
Correct: He was allowed to go to London. [Passive. Can use an antipattern to ignore the passive voice.]
Correct: Why was this situation allowed to occur?

Because I cannot see a pattern that ignores the correct text, I did not make a rule.
