### ISSUE TITLE
[ru] general rule to unify PNN and NN

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#544]
WRONG По сумме всего запускам оптимизации
CORRECT По сумме всех запусков оптимизации

**Comment by yakovru** [comment]
I set this  rule default off because it give many false positives:
https://www.languagetool.org/regression-tests/20161107/result_ru_20161107.html
WRONG example
+Title: <Tatoeba>
+Line 1, column 33, Rule ID: Unify_PNN_NN_number[1]
+Message: Местоимение не согласуется с существительным по числу.
+Скорее всего, это и повлияло на их решение.
+                                ^^^^^^^^^^ 
+
+Title: <Tatoeba>
+Line 1, column 11, Rule ID: Unify_PNN_NN_number[1]
+Message: Местоимение не согласуется с существительным по числу.
+Сколько у тебя близких друзей?
+          ^^^^^^^^^^^^        
+Title: Литва
+Line 1, column 60, Rule ID: Unify_PNN_NN_number[1]
+Message: Местоимение не согласуется с существительным по числу.
+...сле прихода гитлеровцев Временное правительство и его органы были распущены, многие деятели арестованы.

**Comment by kostyfisik** [comment]
@yakovru I hope I will have some to put my hand on after NY.

**Comment by yakovru** [comment]
@kostyfisik   Ok.

**Comment by yakovru** [comment]
Disable the rule, because the noun and pronoun can be linked by different kinds of grammatical links: agreement or government.
Exampes: https://www.languagetool.org/regression-tests/20171120/result_ru_20171120.html

> Целое больше суммы его частей.
> Его целями были:
> Встречая новые слова, ты должен смотреть их значение в словаре.
Closed.
