### ISSUE TITLE
LibreOffice add-on crashes opening a .docx

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6167]
Hello!

When I attempt to open this .docx with LibreOffice 7.2.4 in Windows 10, it crashes:

![languagetool_libreoffice_crash_20211219](https://user-images.githubusercontent.com/5192600/146686247-5eadb798-4b63-4378-ab52-af17af949cbd.png)

Here is the attached document.

Thanks!
[Europass-CV-marcoagpinto_20220101_en_blank.zip](https://github.com/languagetool-org/languagetool/files/7741325/Europass-CV-marcoagpinto_20220101_en_blank.zip)

**Comment by FredKruse** [comment]
@danielnaber The bug is triggered by the missing LT spell checker inside the extension. I wonder if we could introduce some general rule that uses the internal LO/OO spellchecker, when a rule is called by the extension.
 But this seems too difficult for a fast solution before the next release. So, is there a possibility for an easy solution? E.g. set isMisspelled always to true (or false) if englishSpellerRule == null.

**Comment by danielnaber** [comment]
@FredKruse I'm open for quick fixes, but I don't have time now to research and test this myself, sorry.
