### ISSUE TITLE
[office-extension] Looping during the spell check of a text through the spelling and grammar check dialog.

### ISSUE THREAD

**Issue by yakovru** [languagetool-org/languagetool#6183]
Looping during the spelling check of a multilingual text through the spelling and grammar LT check dialog.
The grammar check does not cause an endless loop. 
Step to reproduce:
1. Open test document.
2. Press F7.
3. Set check All or check spelling.
4.  Press "Skip" many times.  The check stops at one word ("yyy" in example).  A new step is performed on the same word.
LanguageTool 5.6-SNAPSHOT (2021-12-22 19:47:29 +0000, 25a447c)
LibreOffice 7.1.2.2 (Win10 x64)

[test_fail.odt](https://github.com/languagetool-org/languagetool/files/7768898/test_fail.odt)
.

**Comment by yakovru** [comment]
@FredKruse

**Comment by FredKruse** [comment]
The bug is caused by a change of language inside the paragraph. This is not well-supported by the LO extension. The solution needs a change to the core components. This can't be done for version 5.6, because it will be released the next days.
I will solve the problem in 5.7 and would be happy, if you could test the new version after the changes are integrated in the 5.7 snapshot.
I will leave a message, when the changes are pushed.

**Comment by yakovru** [comment]
I tested on the latest snapshot (LanguageTool-20220117-snapshot.oxt) and this issue is solved in it.
