### ISSUE TITLE
Slow German spell checker

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#670]
This code makes the German spell checker slow, as it iterates over all words in `spelling.txt` every time, which takes about 1ms per word:

https://github.com/languagetool-org/languagetool/blob/master/languagetool-core/src/main/java/org/languagetool/rules/spelling/SpellingCheckRule.java#L345

@f-knorr Any idea how this could be optimized?

**Comment by danielnaber** [comment]
BTW, examples in the code would be nice, I find e.g. `GermanSpellChecker.ignoreCompoundWithIgnoredWord()` difficult to understand.

**Comment by danielnaber** [comment]
`If there are several matches from the set of ignored words, the length of the longest matching word is returned.` - I don't think this is correct, `Comparator.naturalOrder()` refers to alphabetical order, not to  string length.

**Comment by f-knorr** [comment]
@danielnaber : Sorry to hear that the the code which improves the support for compounds containing ignored words turns out to be a bottleneck.

I have just refactored the code to improve the performance.
1. We now use a regex to check whether a compound may contain a Fugen-S (instead of creating a stream from a Set of String which we check against a word)
2. Instead of using `Comparator.naturalOrder()` the ordering is done by a comparison of String length only (although the Comparator.naturalOrder() implies an ordering by string length)
3. To avoid iterating over all words from spelling.txt I have added a dictionary-like Map, so that only words starting with the same first character are compared. (This is probably the most significant performance improvement)

Can you confirm that the performance has improved?

**Comment by danielnaber** [comment]
> Can you confirm that the performance has improved?

Testing with `org.languagetool.rules.patterns.PerformanceTest` shows a major improvement: from 30ms/sentence to 21ms/sentence. Thanks!

It would be interesting to see whether [a trie](https://commons.apache.org/proper/commons-collections/apidocs/org/apache/commons/collections4/trie/PatriciaTrie.html) helps even more.

**Comment by f-knorr** [comment]
@danielnaber : Glad to read this! I did not know about `org.languagetool.rules.patterns.PerformanceTest`. Grea! I have done some further testing: Switching from `Set` to `List`, `parallelStream` instead of `stream`, or increasing the granularity of the 'dictionary' (i.e., used the first two letters as key to look up words). This did not make things faster (even slightly slower).

So, i doubt that a trie will further improve performance. Maybe I will give it a try anyway...

**Comment by danielnaber** [comment]
Using `parallelStream` should probably be avoided, as the parallelism is set on a higher level already. Also note that you need to check large texts with `PerformanceTest` to see an effect, otherwise everything is overhead. I tried with 20KB text that was checked 5 times.

**Comment by f-knorr** [comment]
ok! I tried with 34KB of text (4 repetitions). Hence, I think the results are reliable. (I tried `parallelStream` just as it was so easy.)
