### ISSUE TITLE
[pt] General POS tagger/synthetizer errors

### ISSUE THREAD

**Issue by Konfekt** [languagetool-org/languagetool#685]
Somehow, `Vi um teorema` gives the error `GENERAL_GENDER_AGREEMENT_ERRORS Erro de concordância de género.`. 

However, in the file `LanguageTool-3.7-SNAPSHOT/org/languagetool/resource/pt/hunspell/pt_PT.dic`, there is correctly listed `teorema/pl	[CAT=nc,G=m,N=s]`. How come the wrong positive still appears? 

Other male words ending in a, like `um pirata`, do not cause this error.

**Comment by TiagoSantos81** [comment]
The file you refered is the spelling dictionary. This issue is with a wrong POS.
The POS recognition is made with files in `LanguageTool-3.7-SNAPSHOT/org/languagetool/resource/pt/`. I will fix these words in the coming days. If you find more POS errors, report them here and I will add them before rebuilding the dictionary and synthetizer.

**Comment by danielnaber** [comment]
As `Vi um teorema` doesn't cause an error anymore, I assume this is fixed - please re-open if I'm wrong.

**Comment by TiagoSantos81** [comment]
I left this open, because this is an issue that is pertinent. 
I fixed the `teorema` tags at the time, but there are still many other words with wrong tags.
I will be happy if they are. That is great help. 
That is also the reason I changed the issue name.

**Comment by TiagoSantos81** [comment]
Reopen?

**Comment by TiagoSantos81** [comment]
Thread is dead. Closing.

**Comment by Konfekt** [comment]
This issue no longer occurs in the latest version.
