### ISSUE TITLE
[LibreOffice extension] Words not added from spelling.txt

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6862]
Hello @FredKruse 

The problem seems to have returned.

I have words in spelling.txt for Portuguese, and they appear as typos in LibreOffice.

I have tried it with the nightly.

![words_not_added_20220702](https://user-images.githubusercontent.com/5192600/176983046-12e50542-9ac4-4539-a579-d9967d3df7dc.png)

**Comment by FredKruse** [comment]
The problem should be solved and compile to Java 8, now.
@danielnaber in German spelling.txt are actual more than 90,000 words. I had to split the dictionary in 4 parts, because of a LO limit to 30,000 words per dictionary. Is there any chance to get this words in the default German dictionary (DE-frami)?

**Comment by danielnaber** [comment]
> Is there any chance to get this words in the default German dictionary (DE-frami)?

Someone would need to check where the words belong, do they actually need to be in the `de_DE.dict` (binary) or the `de_DE.dic` (plain text, from DE-frami with minor changes).
