### ISSUE TITLE
[LibreOffice add-on] LT windows don't disable parent window

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6897]
Hello @FredKruse 

If you go to the menu item “About LanguageTool” it opens a window.

If you click anywhere in LibreOffice, the window becomes hidden behind LibreOffice.

If you then go to “LanguageTool Settings” item menu, it opens another window, and now you have two hidden windows almost impossible to find.

Even if you close LibreOffice, the windows will still be there somewhere.

Could you disable the parent window in these situations?

Thanks!

**Comment by marcoagpinto** [comment]
@FredKruse 

Will “about” and “settings” disable the parent (LibreOffice's) window?

Otherwise, we will click anywhere in LibreOffice while they are open and the window will go to the background (will get hidden).

**Comment by marcoagpinto** [comment]
@FredKruse 

I have tested it.

It works even worse than it did before.

I open the “About window” and it shows an extra icon in the task bar, a Java icon.

Then, I click anywhere on LibreOffice and the “about window” vanishes behind.

Then I go to “LT Settings” and it opens a window.

I click again anywhere on LibreOffice and it vanishes.

It happened that when I close LibreOffice, the “LT Settings” window became minimised at the top of the desktop screen.

Nothing worked on it… it was just a minimised window.

I had to stop the process with task manager, otherwise there wasn't other way of closing that window.


Fred, can't you simply open the windows as child windows and disable the parent window (LibreOffice's)?

Thanks!

**Comment by marcoagpinto** [comment]
```
DisableWindow(libreoffice blah blah, #True)
ShowAboutWindow()
DisableWindow(libreoffice blah blah, #False)
```
I do it this way in the apps I develop with PureBasic, for sure that all language have similar commands.

**Comment by marcoagpinto** [comment]
@FredKruse 

Here is a video screen capture of the issue:


https://user-images.githubusercontent.com/5192600/179085745-0b8752ee-e867-4959-b46e-df9467caa7ac.mp4

Nero Recode cut the image while converting from WMV to MP4. 😢

**Comment by BloomingAzaleas** [comment]
@marcoagpinto  I have been active as a user filing issues and testing LT fixes more recently. Windows 10. You haven't mentioned your platform yet. I suggest you are making hidden assumptions of equivalence between your freedom of action as an app developer and LT's freedom of action as a third-party extension hosted in someone else's office software suite framework -- MULTIPLE someone elses' for LT, in this case, LO. LO provides an API for extensions use and a set of rules about what extensions can and cannot do. If an extension colors outside the lines now LO has cause to frown on that extension. Perhaps you should research whether the LO API and rules for extensions allow the parent window to be disabled as you propose. I think what you are looking for is what in Windows world would be a modal window. So the research question is: "Do LO rules allow extensions to open modal windows?"

I suspect LO will not be happy about an extension that blocks LO's primary functionality GUI threads as LO then becomes hostage to that extension AND sane use of that extension by users who may not realize that, unlike any other LO extension, it blocks LO's GUI responsiveness.

A possible alternative that directly solves your issue is a non-modal "always on top" window, but "always on top" is managed by the desktop window manager.

Regards.

**Comment by marcoagpinto** [comment]
@BloomingAzaleas 

My platform is Windows 10.

I just want to reach near perfection, that is why I am always reporting everything that I find not working as it could.

**Comment by FredKruse** [comment]
The problem was a bit more complex than discussed here. The panels are working of basis of Java swing classes and don't use the LO window GUI. The "About window" was the same as in the standalone application. I wrote an own window for the extension now.
Only one window exists (old will be removed, when a new one is started).
The new window is always pushed to the front (so, nothing can hide, start the window again).
I add the LT logo to the top and give all relevant information needed when a bug shall be reported.

**Comment by BloomingAzaleas** [comment]
@marcoagpinto Of course. I also whanker at LT about obvious bugs and my pet peeve enhancements because A) I am a power-user working on complex documents and B) I see its potential. A difference in approach for enhancements, from my years as an IT systems engineer, is to ask bigger picture questions of myself regards my enhancement ideas. For example, any enhancement request I make will be competing for attention from the LT team among all other enhancement requests. What research, what experimental data, what alternatives, what hypothesis can can I bring to the table in my proposal that will increase its attractiveness to the LT team? You did some of this with the video. What technical or _policy_ constraints might LT have that would be barriers to my proposal and how can I address them? Then there are end-user psychology considerations. How much value would the average, casual LT user get from my enhancement, vice myself as a power-user, and how can I argue that in my proposal? Can the average LT user use my proposed enhancement in a  _reliably_ sane way that will not cause collateral issues for LT? How can I argue that? Is there some aspect of my proposal that would be of value to the LT dev team itself regards behavioral, testing or debugging insight in to LT in the field, and how can I highlight that?  I, as a prior life software dev, always have a temptation to dive right in to code-level implementation ideas. Given I do not know the LT code nor the details of LT's policy constraints, that will just come across as uninformed noise in my proposal to the LT devs. I try to stay at the user-visible behavior level and what that implies about the architecture of LT, vice the code-level implementation of that architecture.

You, as an active software dev, could be a particularly valuable user-space LT contributor with one or two steps back to ask these questions of yourself for your enhancement proposals.

Regards.
