### ISSUE TITLE
[pt] "da" or "de a"?

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7101]
Hello @ricardojosehlima

Look at this sentence:
`Isto reafirma a necessidade da existência da nossa equação para fazer face às necessidades científicas.`

LanguageTool suggests changing “necessidade da” with “necessidade de a”, but it doesn't sound very well to me.

Which one is correct?

Thanks!

**Comment by susanaboatto** [comment]
Hi @marcoagpinto 

This is a false alarm triggered by the infinitive verb "fazer", which does not immediately follow the noun. This rule would apply if "fazer" had "existência" as its subject, which in this case isn't true due to the presence of "para". I think it's best we remove the "skip='-1'" from this rule and include more specific postags in between. I will adjust it now.

**Comment by marcoagpinto** [comment]
Thank you!

❤️
