### ISSUE TITLE
[pt-BR] long check time for string with a lot of hyphen-minus characters

### ISSUE THREAD

**Issue by MadRiv** [languagetool-org/languagetool#717]
languagetool: `v3.7`
```
JLanguageTool languageTool = new JLanguageTool(new BrazilianPortuguese());
long start = System.currentTimeMillis();
languageTool.check("---------------------------");
System.out.printf("duration=%dms", (System.currentTimeMillis() - start));
```
output: `duration=418574ms`
most of time is spent in org.languagetool.rules.spelling.hunspell.HunspellRule#isMisspelled
looks like it happens because of these rules in the pt_BR.aff
```
BREAK ^-
BREAK -$
...
REP -           s-
REP -           r
REP -           s
```

**Comment by danielnaber** [comment]
Thanks for the report. It does indeed not happen with pt-PT. @TiagoSantos81 maybe you know anything about this? Is there a new dictionary available we should use that maybe fixes the issue?

**Comment by TiagoSantos81** [comment]
Well, LanguageTool and LibreOffice are using VERO dictionaries. 
They used to be very active, but the publicly available updates stopped since 10-2013. 
https://pt-br.libreoffice.org/projetos/vero/
We were using an even older version, so I updated moments ago the pt-BR dictionary to that version.
 It  is significantly bigger.

The design of [pt-PT] and [pt-BR] is quite different, but [pt-PT] is much more inflected than [pt-BR] and does not show noticeble performance issues. 
Regarding the REP, well, pt-PT has 3x more and I am inclined to had more, since performance is not an issue for end-users.

I would guess that the problem you face is due to line number (roughly 7x greater).

Anyway, for the [pt-BR] specific maintenace, it is better to contact @MatheusPoletto. 

If the [pt-BR] no has an active maintainer, I will sort it out.

**Comment by danielnaber** [comment]
@TiagoSantos81 seems your update already solved the issue. `---------------------------` is now checked fast. Thanks!
