### ISSUE TITLE
[en] Inconsistent/incorrect tagging of incorrectly capitalized N't as RB causes FN spelling

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#7258]
I cannot think of a sentence for which **N't** is correct as an adverb abbreviation. Thus, **N't** must not get postag RB (compare **n'T**, which doesn't get the postag.)

Snapshot 2022-10-11:
![image](https://user-images.githubusercontent.com/5816160/195284502-2b517f69-980b-4fbd-8b93-b8bf6866bf06.png)

**Comment by jaumeortola** [comment]
The best solution is to write a specific rule that checks these cases: DON't, DoN't, WON't, WoN't...
They are not detected as spelling errors because they are similar to "DO Not" or "Do Not".
Removing the tag will not solve the problem. We would need to change the tokenizer, and I think that doesn't make sense.

**Comment by MikeUnwalla** [comment]
@jaumeortola, thanks for your explanation.
