### ISSUE TITLE
[LO Add-on] Crashed again with the thesis - 2022-10-24

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7333]
Hello @FredKruse 

It crashed again with my thesis.

The thesis is around 500 pages long, I was trying to disable the rule that complains that a sentence is too long.

For months that I have to disable it several times (right-click → deactivate rule) before it takes effect, but now it crashed the add-on after doing it over and over again:

![LO_addon_crash_20221024](https://user-images.githubusercontent.com/5192600/197623154-f1d9c277-4757-49de-9f8f-9a151f6cbb4e.png)

The log that doesn't seem to contain confidential information:
[LanguageTool_dissertation_PhD_20221024.log](https://github.com/languagetool-org/languagetool/files/9855139/LanguageTool_dissertation_PhD_20221024.log)

Could you have a look?

Thanks!

**Comment by FredKruse** [comment]
I think that are two problems. 
First is a not handled null pointer exception. The last update solves this bug. 
The second is, that the deactivating of a rule costs a lot of CPU-time because the text has to be checked once again. So, the user think, there is no change in checking. I changed this behavior by manipulating the cache and set the markups directly. A deactivation of rules by using the right mouse button or the LT check dialog should be much faster. But note: the reactivating of rules take still long time, because of the whole document has to be checked again.

**Comment by marcoagpinto** [comment]
Thank you, @FredKruse
