### ISSUE TITLE
[LibreOffice add-on] Some words appear as typos and in the browser add-on they appear as valid

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7368]
Hello @FredKruse 

Like the subject says (at least in Portuguese European):
`O investigador criou modelos para os vórtices atrás das asas.`

The sentence above flags “vórtices” in my thesis, while if I write the sentence in the browser add-on, there is no typo.

Could you take a look at it?

Thanks!

**Comment by FredKruse** [comment]
@marcoagpinto I tested it in LO as well under Linux as under Windows. There appears no flag in the text.

**Comment by marcoagpinto** [comment]
@FredKruse 

Here is an ODT with it happening:

[LO-addon_appear_as_typo_20221103.odt](https://github.com/languagetool-org/languagetool/files/9927667/LO-addon_appear_as_typo_20221103.odt)

Screenshot:
![LO-addon_appear_as_typo_20221103](https://user-images.githubusercontent.com/5192600/199703513-dedbfb53-846c-4947-a62e-def93f334f7c.png)

**Comment by marcoagpinto** [comment]
@FredKruse 

I have just figured out what is wrong.

It only works with Tiago Santos's pt-PT Hunspell dictionary.

LibreOffice replaced Tiago's version with the latest one from Minho University, which has that word missing.

Anyway, don't the most recent builds of the add-on bring its own dictionary (the one in our repository)?

**Comment by FredKruse** [comment]
@marcoagpinto Yes, the recent builds bring its own dictionaries, but they are used only for purposes of grammar check. LO always use its own dictionaries. 
I tried to find a solution to disable LO spell check and leave the spell checking to LT, but the LO grammar check interface works only with LO spell check enabled.
Otherwise, the extension includes automatically all files with additional words for spell checking as an additional dictionary.
So, there are two possibilities, change the dictionary to Tiago Santos's in LO or add the missing word(s) to the spelling file in LT.

**Comment by marcoagpinto** [comment]
Sure, thanks!
