### ISSUE TITLE
confusion pairs: what's wrong with 'Fux' and 'schänken'?

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool#739]
I just double-checked that the pair x:chs is in de_DE.info, but I don't get the expected suggestions for 'Fux' and 'Büxe'. For 'Wixer', 'Waxtum' and 'waxen' the epected suggestions are at the top of the list. Seems strange.
From my tests it seems pretty obvious that the confusion pairs have a noticeable effect in many cases, e.g. for 'Verschpatüng' I get 'Verspätung', which is pretty cool.

**Comment by danielnaber** [comment]
This looks like a bug in morfologik. Maybe because the character in question is at the end of the word. I've added [a test](https://github.com/languagetool-org/languagetool/blob/6d38df7eda58bfc6b796d91e35fc7debda57f7d5/languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/GermanSpellerRuleTest.java#L369) and will open an issue at morfologik.

**Comment by danielnaber** [comment]
Issue added at https://github.com/morfologik/morfologik-stemming/issues/91

**Comment by janschreiber** [comment]
A similar problem with ä/e which I added today: I get the expected result for 'präkere', but for 'schänken' I still get 'Schänken' as the only result. 'schenken' should be number 2 in the list of suggestions I think, but it isn't there.

**Comment by danielnaber** [comment]
"Fux -> Fuchs" is fixed now, "schänken" seems to be yet another issue.

**Comment by danielnaber** [comment]
The schänke/schenke issue now has an issue at https://github.com/morfologik/morfologik-stemming/issues/94

**Comment by danielnaber** [comment]
Seems to be fixed thanks to Morfologik update.
