### ISSUE TITLE
Problem with PM_IN_THE_EVENING Rule

### ISSUE THREAD

**Issue by KnowZero** [languagetool-org/languagetool#740]
The rule should double check if there is an ending "."

If you go to the front page:

https://www.languagetool.org/

And click on the suggestion, you end up with P.M.. (which is again a mistake which needs to be fixed twice)

How about changing the rule to and eating up the dot if it exists:

```xml
<!-- English rule, 2017-07-14 -->
<rule id="" name="">
 <pattern>
  <token regexp='yes'>1?\d</token>
  <marker>
  <token>P</token>
  <token>.</token>
  <token>M</token>
  <token>.</token>
  <token>in</token>
  <token>the</token>
  <token regexp='yes'>(?:evening|afternoon)(?:\.|)</token>
  </marker>
 </pattern>
 <message>Consider using <suggestion>P.M.</suggestion></message>
 <short>Redundant phrase</short>
 <example correction=''>It's 5 <marker>P.M. in the afternoon</marker>.</example>
 <example>It's 5 P.M.</example>
</rule>
```

**Comment by f-knorr** [comment]
Thank you for reporting this really annoying bug. I have just fixed it.
And thanks for suggesting a possible fix. Unfortunately, I could not copy it because each token has to checked / analyzed on its own and a dot (".") is a new `<token/>`.
Here is an [introduction to writing rules for LanguageTool](http://wiki.languagetool.org/development-overview).
