### ISSUE TITLE
[uk] Wrong translation "стрілочна" → "стрілкова"

### ISSUE THREAD

**Issue by matrunchyk** [languagetool-org/languagetool#7449]
Hi there.

The language tool recognizes the word "стрілкова" as invalid, though we have this in a dictionary: http://sum.in.ua/s/strilochnyj
On the other hand, "стрілочна" (the suggestion by Language Tool) doesn't exist in the dictionary.

Can we fix it somehow via tokenization?

cc @arysin

**Comment by arysin** [comment]
Hmm, I've just tried on https://languagetool.org and see "стрілкова" ок and "стрілочна" - bad
![image](https://user-images.githubusercontent.com/5498716/202914119-addea0b6-f878-42fe-81b1-290a8e86c43a.png)

If you meant to treat "стрілочний" as ok, then it's not a recommended word:
https://e2u.org.ua/s?w=%D1%81%D1%82%D1%80%D1%96%D0%BB%D0%BA%D0%BE%D0%B2%D0%B8%D0%B9&dicts=all&highlight=on&filter_lines=on
https://r2u.org.ua/s?w=%D1%81%D1%82%D1%80%D1%96%D0%BB%D0%BA%D0%BE%D0%B2%D0%B8%D0%B9&scope=all&dicts=all&highlight=on
Також тут є стрілковий: https://svc2.ulif.org.ua/dictua/
СУМ is not the best source to verify the words, most of it was composed during Soviet times.

**Comment by matrunchyk** [comment]
@arysin ahh I see, cool, so in that case, we'll be relying on the sources you mentioned in products, and not on СУМ.

Clothing this one, thank you for the quick response and explanations!

**Comment by matrunchyk** [comment]
Hmm there actually are both "стрілочний" and "стрілковий" in https://svc2.ulif.org.ua/dictua/
Can we assume that both are correct?

**Comment by arysin** [comment]
Well, unfortunately there's not since source of truth here. There are lots of official dictionaries that are mostly fixing what was used during the last 70 years, and most of them are based on Soviet-era sources.
Also there are lots of opinions and thoughts on what's right and what's wrong. Sometimes even well-known linguists don't agree on some points.
Ukrainian team for LanguageTool did a lot of research for the past 10 years on many words and grammar topics, and although we try to discourage things that were pushed during Soviet times to make Ukrainian closer to Russian, we try not to make the rules too puristic. Some contradicting aspects we implement as a "style" rules with long explanatory messages.
In general, https://r2u.org.ua and https://e2u.org.ua sites have lots of great dictionaries that allow you to analyze things in perspective. But if you need a quick reference, you could use our VESUM dictionary: https://r2u.org.ua/vesum
It's a biggest Ukrainian dictionary that's constantly updated and verified by testing LT rules on huge archives of modern media.
Usually the words we consider not correct are marked with tag ":bad"
