### ISSUE TITLE
[pt] Wrong correction

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#7574]
The sentence
São 4 formulários, cada um sobre um assunto.

generated the "error"
Erro de pontuação: Separe elementos de uma enumeração com vírgulas. And the suggestion: sobre, um.

**Comment by marcoagpinto** [comment]
Ahhhh…

Ricardo, I noticed that LanguageTool has been suggesting commas for many sentences in Portuguese.

I believe it must be @susanaboatto who has been working on it.

Susana, are you creating comma rules? Could you please take a look at this if it is you?

Thanks!

**Comment by susanaboatto** [comment]
Hi @ricardojosehlima, this error was not triggered for me, but I think it might be caused by `ENUMERATION_COMMAS`, because "sobre" is tagged as a noun for some reason. If I remove it as a tag, several rules cease to work. So, I have added exceptions to `ENUMERATION_COMMAS`. Let's see if this solves the problem.

@marcoagpinto Other comma suggestions are likely triggered by our AI rule. Do you see any problem with them?

**Comment by ricardojosehlima** [comment]
Ok thanks!

**Comment by marcoagpinto** [comment]
@susanaboatto 

I haven't had any issues with commas that I can remember of.
