### ISSUE TITLE
[ca] check place names

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#7603]
Check place names in dictionary with new publication by IEC: 

https://nomenclator-mundial.iec.cat/cerca.asp?opcio=1&pclau=%25&button=Cercar

**Comment by Pepmaquina** [comment]
The words in this file are not recognized by LT. It could be for me very usefully if it is possible to includer in tagger dictionary.
I discarded in this collection the words that have some kind of doubts in spelling.
[Nomenclàtor_filtrat.ods](https://github.com/languagetool-org/languagetool/files/10464422/Nomenclator_filtrat.ods)

**Comment by jaumeortola** [comment]
Thank you! Could you share the discarded words? I would like to see them.

**Comment by Pepmaquina** [comment]
There are several kinds of troubles.
First, these words have changed orthographic.

Zúric 
Mississipi
Mulhacén 
Múnic 
Cancún

Other troubles could be caused by me I need more time to analyze.
As soon that I'll revise it, I'll send you more words by especial characters not used in Catalan.

There is a word "óblast" that means a region of Russia, it appears several times in nomenclator, this word is not included in any dictionary that I know, but Wikipedia.

Another question for me is the need to put an article before toponym, like:
el Vendrell, sa Pobla, el Perú,
I read remarks about that, but not find any list that indicates when it can use or no. 

Probably now can find it in the IEC nomenclator.

**Comment by Pepmaquina** [comment]
Hi. I don't understand why appears “?” symbols in the list, but not on the map.
https://nomenclator-mundial.iec.1057 4747 5116 9482 6699 1541/estats_mapa.asp?estat=Vietnam

It's not finished the job of IEC or is a bad codification?

**Comment by jaumeortola** [comment]
Mostly done.
