### ISSUE TITLE
False Positive for Grammatical Error

### ISSUE THREAD

**Issue by greyrock** [languagetool-org/languagetool#7718]
Using the API (https://api.languagetoolplus.com/v2/check), when I run this text:
" Additionally, if you start off by doing some passive stretches first then transition into active ones later on, those same poses will become easier as your body starts warming up from the activity before. Thus when done afterwards, these low intensity positions create better range of motion over time—increasing strength and balance too!"

LanguageTools is suggesting I replace 'as' with 'than'. But, to me, it seems like a weird suggestion. I was curious as to why it said that, and how I might avoid such suggestions in the future.

{
“message”: “Comparison requires “than”, not ‘then’ nor ‘as’.”,
“shortMessage”: “Grammatical problem: use ‘than’”,
“replacements”: [
{
“value”: “than”,
“shortDescription”: “used in comparisons”
}
],
“offset”: 149,
“length”: 2,
“context”: {
“text”: “…on, those same poses will become easier as your body starts warming up from the ac…”,
“offset”: 43,
“length”: 2
},
“sentence”: “Additionally, if you start off by doing some passive stretches first then transition into active ones later on, those same poses will become easier as your body starts warming up from the activity before.”,
“type”: {
“typeName”: “Other”
},
“rule”: {
“id”: “COMP_THAN”,
“subId”: “3”,
“sourceFile”: “grammar.xml”,
“description”: “Comparison with ‘than’, e.g. ‘bigger then (than)’”,
“issueType”: “grammar”,
“category”: {
“id”: “GRAMMAR”,
“name”: “Grammar”
},

**Comment by tiff** [comment]
Thanks for reporting. Germans commonly confuse "as" with "than" (because the German word for "than" is "als").
Since we already have some specific rules that only target German mother tongue speakers, 
I have fixed this any many other issues of the affected rule as part of https://github.com/languagetool-org/languagetool/commit/041bd3f88306cb39f2b31cbc626d5822c309de3f

Now it is much better as before :)
