### ISSUE TITLE
[de] What's wrong with the sentence "Verzichten Sie also auf Captchas"

### ISSUE THREAD

**Issue by orschiro** [languagetool-org/languagetool#778]
In order to discuss this, is it the right approach to post this here?

In my opinion, no comma is needed here.

![peek 2017-08-19 07-06](https://user-images.githubusercontent.com/170947/29483704-26e0edf4-84ad-11e7-8b98-049076435f11.gif)

**Comment by janschreiber** [comment]
I agree, that's false positive.

**Comment by orschiro** [comment]
Can I help somehow to fix it?

**Comment by f-knorr** [comment]
The sentence "Verzichten Sie also auf Captchas." does not raise an error. In the particular example, the preceding time steps are interpreted to be part of the sentences. That's why "Verzichten" is not recognized as a verb form. 
A solution to this problem would be modify the sentence tokenization so that "Verzichten" is recognized as the start of a new sentence.

**Comment by orschiro** [comment]
> A solution to this problem would be modify the sentence tokenization so that "Verzichten" is recognized as the start of a new sentence.

Maybe another option would be to recognise that the above is a timestamp and not a "real" sentence?

**Comment by f-knorr** [comment]
> Maybe another option would be to recognise that the above is a timestamp and not a "real" sentence?
Recognizing the time-stamp as a time-stamp does not necessarily help. Only if "Verzichten" is interpreted as a sentence start, the upper-case word "Verzichten" is also considered as a verb form of the lowe-case verb "verzichten"

**Comment by f-knorr** [comment]
Should be fixed by 
https://github.com/languagetool-org/languagetool/commit/74a36e24da84f7c12e0f8be42a1d4c4b4118124a

**Comment by orschiro** [comment]
Thank you, @f-knorr. :-)
