### ISSUE TITLE
[de] compounds.txt not working as good as it should

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#779]
I've just noticed that compounds.txt doesn't work as good as it should. I am writing from a German perspective but this might be applicable to other languages too:

German compounds that are written as a single word without hyphen (`Firstpartsecondpart`) are entered into the file as `Firstpart-secondpart+`. If a user now enters `Firstpart secondpart` into LanguageTool, he/she'll get the message that it should be written as one word. So far so good.

But if you look at compounds that are built from two nouns, many Germans do write `Firstpart Secondpart` and this mistake is not registered by LanguageTool.

As an example:
Correct: Dopplereffekt
Incorrect (detected): Doppler effekt
Incorrect (not detected): Doppler Effekt

I do understand that there are good reasons why the detection is case-sensitive. But maybe it can be tweaked in a way that it also works if the second part of the word is written with a capital letter.

**Comment by janschreiber** [comment]
Good catch. I wonder why we never noticed this, for Christ's sake. Note to self: Test later today whether it helps if we uppercase the second part: Firstpart-Secondpart+.

**Comment by Discostu36** [comment]
It does work for the detection but then the suggestion is wrong  (DopplerEffekt).

**Comment by f-knorr** [comment]
I have just committed some changes that address the problem described here.
It is now possible to enter "Doppler-Effekt?" in compounds.txt so that "Doppler Effekt" raises an error and the suggestion offered is "Dopplereffekt". (Note that Doppler-Effekt is correct and will not raise an error.)
Right now, I do not see any point in extending this issue any further. "Doppler effekt" will raise a spelling error on "effekt" which overrules the compound rule. If there is a real need to raise an error on "Doppler effekt" add the additional line "Doppler-effekt+" to compounds.txt

**Comment by Discostu36** [comment]
Thanks! Sadly, also the first category (hyphen or no hyphen) doesn't work correctly. If I enter "Bestseller Roman" the suggestions are "Bestseller-Roman" (correct) and "BestsellerRoman" (incorrect).

**Comment by f-knorr** [comment]
ok. I have added another suffix: If you add "$", the non-hyphenated variant will use lower-cased compounds for concatenation. Can we close this issue?

**Comment by Discostu36** [comment]
Yes, thank you very much!
