### ISSUE TITLE
LibreOffice plugin - TextLevelRules are only working on the level of paragraphs

### ISSUE THREAD

**Issue by TiagoSantos81** [languagetool-org/languagetool#781]
Reported on issue #669
 @FredKruse
«
There are two points left so far I see:

A way should be found to analyze the whole text.
»

**Comment by FredKruse** [comment]
The used interface for text proof of LibreOffice operates on the paragraph level. The paragraphs are proofed in an arbitrary way.
I tried some ideas to realize a full text search. Unfortunately everything failed because I didn't found a way to get the position of the proofed paragraph. So I can't assign the errors of the full text proof to the paragraph proofed by the doProofReading of the interface.
If somebody has an idea to get the position of the paragraph to be proofed, please let me know.

**Comment by danielnaber** [comment]
This has been fixed now, hasn't it?

**Comment by FredKruse** [comment]
Yes, the issue can be closed
