### ISSUE TITLE
[es] Errors not detected

### ISSUE THREAD

**Issue by f-knorr** [languagetool-org/languagetool#796]
The following errors are not detected according to a user of the LT Firefox extension:
I write:

El niño esta en la guarderia
LanguageTool corrects me:
El niño esta en la guardería

The right thing is:
El niño está en la guardería

other:
eso esta echo
LanguageTool:
eso esta echo

The right thing is:
Eso está hecho

**Comment by danielnaber** [comment]
Maybe @jmartorell can have a look.

**Comment by jaumeortola** [comment]
See: https://github.com/languagetool-org/languagetool/commit/b9d7787762a8435b3f2b025645d1c15c32279ad8 and https://github.com/languagetool-org/languagetool/commit/fc97223f010317d4c363d9047aee199e789c7284
It's not perfet, but it's better than nothing. These rules are important because these errors are very frequent in Spanish. Some cases are very difficult, so a few false positives/negatives are expected.

**Comment by f-knorr** [comment]
I think we can close this issue for now. Thank you, @jaumeortola .
