### ISSUE TITLE
[en] on/in my mind - 2023-03-12

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8015]
Hello!

`This code looks so simple that it creates this doubt on my mind.`

It suggests changing “on” with “in”.

I thought that it was written “on”?

Could someone check just to be sure?

Thanks!

**Comment by evan-defran-lt** [comment]
Hi @marcoagpinto!

LT is right in this situation. 

It's somewhat complicated, because both `on my mind` and `in my mind` are perfectly valid phrases in English, and `in` and `on` are closely related in meaning. 

Generally, `on the mind` is part of an idiomatic expression (i.e., _to have something on your mind_) that means that you're worried about something or preoccupied by something. 

Meanwhile, English speakers tend to metaphorically construe the mind as a box, so we refer to ideas/doubts/etc. being _in_ the mind. 

Of course, there are some exceptions. 

It's not a perfect tool, but [Google's ngram viewer](https://books.google.com/ngrams/graph?content=doubt+on+my+mind%2Cdoubt+in+my+mind&year_start=1800&year_end=2019&corpus=en-2019&smoothing=3) also sheds some light about the situation.
