### ISSUE TITLE
[LibreOffice + Java 9] LanguageTool doesn't work

### ISSUE THREAD

**Issue by RudyMas** [languagetool-org/languagetool#830]
The moment you start typing, LibreOffice hangs for a moment and then LanguageTool 3.9 crashes.

I had to reinstall Java 8 and set it as the JRE to use in LibreOffice to make it work again.

**Comment by danielnaber** [comment]
Thanks for the report - which version of LibreOffice have you been using? What exactly does "crash" mean, did you get an error message?

**Comment by RudyMas** [comment]
LibreOffice 5.4.3.2 (x64)
Java 9.0.1 (x64)
![capture](https://user-images.githubusercontent.com/17342220/32669697-ba411fee-c641-11e7-9617-312c2a96bc5f.PNG)

![capture1](https://user-images.githubusercontent.com/17342220/32669761-ecc76734-c641-11e7-8251-2725b06b2ce6.PNG)

With Java8 (latest version) eveything is fine.

**Comment by MartinPC** [comment]
I have the same problem with nearly identical pop-ups, using:

LanguageTool 3.9
LibreOffice 5.4.**4**.2 (x64)
Windows **7** (x64)
Java 9.0.1 (x64)

For now, I have reinstalled Java 8 update 144 (x64) and selected it ("1.8.0_144") instead of 9.0.1 in _Tools > Options > Advanced_  -- thanks for the tip, RudyMas -- but I hope LanguageTool will eventually work with newer versions of Java.

**Comment by MartinPC** [comment]
**IMPORTANT CORRECTION:**

The Java 8 update 144 installer was the latest one I had downloaded before moving to Java 9, and that's why I reinstalled it. I've since learned that **update 144 has critical security vulnerabilities** that have been **patched in Java 8 update 151.** Accordingly, I uninstalled Java 8 update 144, downloaded and installed Java 8 update 151, and told LibreOffice to use the latter. (And LanguageTool still isn't crashing.)

**Comment by arysin** [comment]
I think we fixed Java 9 in LT 4.0 (with a07ecbc75f72ee7c916fcf9408dea428a866ac9c), can you please try?

**Comment by RudyMas** [comment]
I can confirm it. Just installed Java 9.0.1 again, configured LibreOffice to use this version of Java and then opened a document and started typing without getting an error message.

LanguageTool did also its job by recognizing the spelling mistakes I made on purpose.

Thanks for fixing it!

**Comment by MartinPC** [comment]
I switched to Java 9.0.1 in _Tools > Options > Advanced_ and, after a restart, I'm still getting error pop-ups.
![4 2018-01-08 post-fix language tool error in lo 5 4 4 2 x64 for windows - both pop-ups](https://user-images.githubusercontent.com/3917183/34696294-223b0634-f4c6-11e7-9638-c37ed26e625c.PNG)
![5 2018-01-08 post-fix language tool error in lo 5 4 4 2 x64 for windows - top pop-up](https://user-images.githubusercontent.com/3917183/34696295-2255483c-f4c6-11e7-96f3-6a8f90627244.PNG)
![6 2018-01-08 post-fix language tool error in lo 5 4 4 2 x64 for windows - bottom pop-up](https://user-images.githubusercontent.com/3917183/34696297-2273732a-f4c6-11e7-90f9-5937cd9a6ef6.PNG)

**Comment by arysin** [comment]
@MartinPC you need to update to LanguageTool 4.0

**Comment by MartinPC** [comment]
Oops! I have to run right now, but I'll attend to it when I get back in and post my results. Thank you!

**Comment by MartinPC** [comment]
No problems now -- it's _amazing_ how _actually installing_ the updated extension fixed the problem! Thanks very much, and sorry for inflicting my "senior moment" on you!
