### ISSUE TITLE
Wrong offset for German when text contains emojis

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#842]
<img width="1001" alt="bildschirmfoto 2017-11-22 um 11 05 08" src="https://user-images.githubusercontent.com/37363/33121564-6d16414e-cf75-11e7-9bed-a81dd4bb075d.png">

### Expected behavior:
the word ``get``should be highlighted not the third emoji. Interestingly this doesn't happen with the second sentence. Looks like the offset of the first misspelling counts an emoji as one character while the second misspelling counts an emoji as two characters.
I also experienced this issue while using the LanguageTool API on [SpellBoy.com](https://www.spellboy.com/). 

### English seems to be fine:
<img width="1002" alt="bildschirmfoto 2017-11-22 um 11 05 01" src="https://user-images.githubusercontent.com/37363/33121621-a6e1301e-cf75-11e7-9480-384d32284797.png">

**Comment by tiff** [comment]
@f-knorr thank you!

**Comment by danielnaber** [comment]
I think the fix was not complete, it still happens with two emojis, but not with one:

![emoji1](https://user-images.githubusercontent.com/857004/33281471-acdafc00-d3a5-11e7-9f3f-cdcae874fb7f.png)
![emoji](https://user-images.githubusercontent.com/857004/33281473-aee5851a-d3a5-11e7-8e58-cf3c6b634dfa.png)

**Comment by f-knorr** [comment]
You are right the fix is incomplete. I have just finished a better fix, but it needs some testing...
