### ISSUE TITLE
[pt] Tone tags

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8727]
Hello @susanaboatto @jaumeortola @maphjo 

I noticed that there are new tags.

Where can I find their list and description?

Thanks!

**Comment by marcoagpinto** [comment]
Any special recommendations on/where to use them?

**Comment by marcoagpinto** [comment]
😋

**Comment by marcoagpinto** [comment]
@ricardojosehlima

😋

**Comment by maphjo** [comment]
@marcoagpinto Yes, you can. But I would like to ask you to create PRs and set @susanaboatto as a reviewer so that she can add the new attributes we have created and are currently testing. :heart:

**Comment by marcoagpinto** [comment]
Ahhhhh… 😄 

I don't know how to create PRs with TortoiseSVN.

It is better for me to only improve rules already in the XMLs, like adding antipatterns and subrules, until all is operational.

This is the best option.

Thanks!

**Comment by marcoagpinto** [comment]
And the nightlies don't work any more with the latest LibreOffice, so I can't test on my thesis.

**Comment by maphjo** [comment]
> I don't know how to create PRs with TortoiseSVN.

I think it will make sense for you to switch to TortoiseGIT to be able to properly use the GIT functionalities. To create a Pull Request (PR), first you will have to create a new branch, make the changes there, commit and push the new branch. You will then see the possibility to create a PR.
A PR will give you the possibility to ask Susana for a review of your chances before merging. Internally, always create Pull Requests and ask for reviews to avoid errors due to typos.
I cannot give you any help with TortoiseGIT, but I am sure that there are tutorials which will walk you through the process.
Just give it a try. :relaxed:  

Also, after we have finished the introduction of the new style feature, there will definitely be a few questions in the beginning which you will be able to easily address with a pull request. :wink:
