### ISSUE TITLE
[pt] Creating a rule “Expressão prolixa” from wordiness-pt.txt - 2023-07-13

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8932]
Heya, @p-goulart 

Look at these sentences in wordiness-pt.txt:
```
considerada como=considerada
consideradas como=consideradas
considerado como=considerado
considerados como=considerados
```

They cause a false positive in the sentence:
`Nem todos os conflitos são considerados como sendo guerra.`

So, the best is to convert it into a rule.

I can code the rule today.

Do you believe it is a good idea?

If so, could you please tell me the rule name, tone type and message, so that I get everything right on my first try?

Thanks!

**Comment by p-goulart** [comment]
We don't have any formalised guidelines for the naming of rules or the writing of messages, so unfortunately it's difficult to tell you in advance what those should look like.

There's some internal work we're doing that should help us with the writing of consistent, informative messages, and it'll probably go hand in hand with coming up with concrete guidelines, but we're not there yet.

As for the rule IDs, for now, all we ask is that they are correctly spelt, somewhat transparent and unambiguous, and dialect-agnostic. That's why I specifically wanted us to avoid 'nome' in favour of 'substantivo'.

The tone tags are described in our [documentation](https://languagetooler.atlassian.net/wiki/spaces/DEV/pages/2148630563/toneTags), though. If after reading that you still don't know where your new rules fit, let us know and we'll revise that documentation to make it clearer.

---

> so that I get everything right on my first try?

That's not really how this works! The whole point of code review is that getting everything right on your first attempt is not a reasonable expectation. Do whatever you think is best given what you already know about the project and the available documentation, and if we have any concerns about it we'll let you know in the PR.

**Comment by marcoagpinto** [comment]
Ohhhh… OK, I will try the best I can.

😋 😋 😋 😋 😋
