### ISSUE TITLE
Missing Words English Dictionary

### ISSUE THREAD

**Issue by Krabbenhoft** [languagetool-org/languagetool#9598]
There seems to be a lot of words missing from the English dictionary, particularly forms of words. "Unoffended" for example is a very well documented word but is not recognized.

**Comment by Krabbenhoft** [comment]
"Unadmirable" was the other word that brought this issue to my attention.

**Comment by tiff** [comment]
@AzadehSafakish @jaumeortola from my own experience I can confirm that many adjectives with "un" are missing from our dictionary. I wonder if there's a systematical way of extending our dictionary with such words.

**Comment by AzadehSafakish** [comment]
Both "unoffended" and "unadmirable" + all derivational morphology can be found in our dictionary (this is the version I have, may be out of date):
[english.zip](https://github.com/languagetool-org/languagetool/files/13251279/english.zip)

The words are tagged, but they are not recognized by our speller.
Does anyone know why this is?
I guess I can see a problem with words that could also resemble typos; maybe that's why we don't automatically ignore their spelling.
I opened [an issue](https://github.com/languagetooler-gmbh/languagetool-premium/issues/6637) to add all tagged but unrecognized words to ignore/spelling (provided they don't resemble typos).

I can start with the "un-" words.

**Comment by Nyabinary** [comment]
"hubristic" is another missing word as well.
